            <!-- BEGIN: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="c-layout-breadcrumbs-1 c-subtitle c-fonts-uppercase c-fonts-bold c-bordered c-bordered-both">
                <div class="container">
                    <div class="c-page-title c-pull-left">
                        <h3 class="c-font-uppercase c-font-sbold"><?php echo $this->translate('Order History');?></h3>
                        <h4 class="">Page Sub Title Goes Here</h4>
                    </div>
                    <ul class="c-page-breadcrumbs c-theme-nav c-pull-right c-fonts-regular">
                        <li><a href="javascript:;" ng-click="changeTemplateURL('/ef-welcome');"><?php echo $this->translate('Shop');?></a></li>
                        <li>/</li>
                        <li><a href="javascript:;"><?php echo $this->translate('Order History');?></a></li>
                    </ul>
                </div>
            </div>
            <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="container">
				<?php echo $this->partial('shop/customer/leftmenu');?>
				
                <div class="c-layout-sidebar-content ">
                    <!-- BEGIN: PAGE CONTENT -->
                    <!-- BEGIN: CONTENT/SHOPS/SHOP-ORDER-HISTORY-2 -->
                    <div class="c-content-title-1">
                        <h3 class="c-font-uppercase c-font-bold"><?php echo $this->translate('Order History');?></h3>
                    </div>
                    <div class="row c-margin-b-40 c-order-history-2">
                        <div class="row c-cart-table-title">
                            <div class="col-md-2 c-cart-image">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Image');?></h3>
                            </div>
                            <div class="col-md-1 c-cart-ref">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Order');?></h3>
                            </div>
                            <div class="col-md-2 c-cart-desc">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Font');?></h3>
                            </div>
                            <div class="col-md-2 c-cart-price">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Price');?></h3>
                            </div>
                            <div class="col-md-3 c-cart-total">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Payment Method');?></h3>
                            </div>
                            <div class="col-md-2 c-cart-qty">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Date');?></h3>
                            </div>
                        </div>
                        <!-- BEGIN: ORDER HISTORY ITEM ROW -->
                        <div class="row c-cart-table-row">
                            <h2 class="c-font-uppercase c-font-bold c-theme-bg c-font-white c-cart-item-title c-cart-item-first"><?php echo $this->translate('Item');?> 1</h2>
                            <div class="col-md-2 col-sm-3 col-xs-5 c-cart-image">
                                <img src="http://placehold.it/1200x900" /> </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-ref">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold"><?php echo $this->translate('Order');?></p>
                                <p>#1103</p>
                            </div>
                            <div class="col-md-2 col-sm-6 col-xs-6 c-cart-desc">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold"><?php echo $this->translate('Description');?></p>
                                <p>
                                    <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="c-font-bold c-theme-link c-font-dark">Acumin Pro</a>
                                </p>
                            </div>
                            <div class="clearfix col-md-2 col-sm-3 col-xs-6 c-cart-price">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold"><?php echo $this->translate('Price');?></p>
                                <p class="c-cart-price c-font-bold">$147.00</p>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6 c-cart-total">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold"><?php echo $this->translate('Payment Method');?></p>
                                <p class="c-cart-price c-font-bold">Credit Cart (MasterCard)</p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-qty">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold"><?php echo $this->translate('Date');?></p>
                                <p>2 Sep 2015</p>
                            </div>
                        </div>
                        <!-- END: ORDER HISTORY ITEM ROW -->
                        <!-- BEGIN: ORDER HISTORY ITEM ROW -->
                        <div class="row c-cart-table-row">
                            <h2 class="c-font-uppercase c-font-bold c-theme-bg c-font-white c-cart-item-title">Item 2</h2>
                            <div class="col-md-2 col-sm-3 col-xs-5 c-cart-image">
                                <img src="http://placehold.it/1200x900" /> </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-ref">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Order</p>
                                <p>#1106</p>
                            </div>
                            <div class="col-md-2 col-sm-6 col-xs-6 c-cart-desc">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Description</p>
                                <p>
                                    <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="c-font-bold c-theme-link c-font-dark">Litania </a>
                                </p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-price">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Price</p>
                                <p class="c-cart-price c-font-bold">$99.00</p>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6 c-cart-total">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Payment Method</p>
                                <p class="c-cart-price c-font-bold">PayPal</p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-qty">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Date</p>
                                <p>5 Sep 2015</p>
                            </div>
                        </div>
                        <!-- END: ORDER HISTORY ITEM ROW -->
                        <!-- BEGIN: ORDER HISTORY ITEM ROW -->
                        <div class="row c-cart-table-row">
                            <h2 class="c-font-uppercase c-font-bold c-theme-bg c-font-white c-cart-item-title c-cart-item-first">Item 3</h2>
                            <div class="col-md-2 col-sm-3 col-xs-5 c-cart-image">
                                <img src="http://placehold.it/1200x900" /> </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-ref">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Order</p>
                                <p>#1107</p>
                            </div>
                            <div class="col-md-2 col-sm-6 col-xs-6 c-cart-desc">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Description</p>
                                <p>
                                    <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="c-font-bold c-theme-link c-font-dark">Karmina </a>
                                </p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-price">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Price</p>
                                <p class="c-cart-price c-font-bold">$82.00</p>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6 c-cart-total">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Payment Method</p>
                                <p class="c-cart-price c-font-bold">Credit Cart (MasterCard)</p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-qty">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Date</p>
                                <p>7 Sep 2015</p>
                            </div>
                        </div>
                        <!-- END: ORDER HISTORY ITEM ROW -->
                        <!-- BEGIN: ORDER HISTORY ITEM ROW -->
                        <div class="row c-cart-table-row">
                            <h2 class="c-font-uppercase c-font-bold c-theme-bg c-font-white c-cart-item-title c-cart-item-first">Item 4</h2>
                            <div class="col-md-2 col-sm-3 col-xs-5 c-cart-image">
                                <img src="http://placehold.it/1200x900" /> </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-ref">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Order</p>
                                <p>#1123</p>
                            </div>
                            <div class="col-md-2 col-sm-6 col-xs-6 c-cart-desc">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Description</p>
                                <p>
                                    <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="c-font-bold c-theme-link c-font-dark">Kinescope </a>
                                </p>
                            </div>
                            <div class="clearfix col-md-2 col-sm-3 col-xs-6 c-cart-price">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Price</p>
                                <p class="c-cart-price c-font-bold">$54.00</p>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6 c-cart-total">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Payment Method</p>
                                <p class="c-cart-price c-font-bold">PayPal</p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-qty">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Date</p>
                                <p>8 Sep 2015</p>
                            </div>
                        </div>
                        <!-- END: ORDER HISTORY ITEM ROW -->
                        <!-- BEGIN: ORDER HISTORY ITEM ROW -->
                        <div class="row c-cart-table-row">
                            <h2 class="c-font-uppercase c-font-bold c-theme-bg c-font-white c-cart-item-title c-cart-item-first">Item 5</h2>
                            <div class="col-md-2 col-sm-3 col-xs-5 c-cart-image">
                                <img src="http://placehold.it/1200x900" /> </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-ref">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Order</p>
                                <p>#1136</p>
                            </div>
                            <div class="col-md-2 col-sm-6 col-xs-6 c-cart-desc">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Description</p>
                                <p>
                                    <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="c-font-bold c-theme-link c-font-dark">Brandon Grotesque</a>
                                </p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-price">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Price</p>
                                <p class="c-cart-price c-font-bold">$135.00</p>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6 c-cart-total">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Payment Method</p>
                                <p class="c-cart-price c-font-bold">Credit Cart (Visa)</p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-qty">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Date</p>
                                <p>10 Sep 2015</p>
                            </div>
                        </div>
                        <!-- END: ORDER HISTORY ITEM ROW -->
                    </div>
                    <!-- END: CONTENT/SHOPS/SHOP-ORDER-HISTORY-2 -->
                    <!-- END: PAGE CONTENT -->
                </div>
            </div>
