            <!-- BEGIN: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="c-layout-breadcrumbs-1 c-subtitle c-fonts-uppercase c-fonts-bold c-bordered c-bordered-both">
                <div class="container">
                    <div class="c-page-title c-pull-left">
                        <h3 class="c-font-uppercase c-font-sbold"><?php echo $this->translate('Customer Dashboard');?></h3>
                        <h4 class="">Page Sub Title Goes Here</h4>
                    </div>
                    <ul class="c-page-breadcrumbs c-theme-nav c-pull-right c-fonts-regular">
                        <li><a href="javascript:;" ng-click="changeTemplateURL('/ef-welcome');">Shop</a></li>
                        <li>/</li>
                        <li><a href="javascript:;"><?php echo $this->translate('Customer Dashboard');?></a></li>
                    </ul>
                </div>
            </div>
            <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="container">
				<?php echo $this->partial('shop/customer/leftmenu');?>
                <div class="c-layout-sidebar-content ">
                    <!-- BEGIN: PAGE CONTENT -->
                    <!-- BEGIN: CONTENT/SHOPS/SHOP-CUSTOMER-DASHBOARD-1 -->
                    <div class="c-content-title-1">
                        <h3 class="c-font-uppercase c-font-bold"><?php echo $this->translate('My Dashboard');?></h3>
                        <div class="c-line-left"></div>
                        <p class=""> <?php echo $this->translate('Hello');?>
                            <a href="#" class="c-theme-link">Joe Doe</a> (<a href="#" class="c-theme-link"><?php echo $this->translate('not Joe Doe? Sign out');?></a>).
                            <br /> </p>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12 c-margin-b-20">
                            <h3 class="c-font-uppercase c-font-bold">Joe Doe</h3>
                            <ul class="list-unstyled">
                                <li>25, Lorem Lis Street, Orange C, California, US</li>
                                <li>Phone: 800 123 3456</li>
                                <li>Fax: 800 123 3456</li>
                                <li>Email:
                                    <a href="mailto:example@example.com" class="c-theme-link">example@example.com</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- END: CONTENT/SHOPS/SHOP-CUSTOMER-DASHBOARD-1 -->
                    <!-- END: PAGE CONTENT -->
                </div>
            </div>