            <!-- BEGIN: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="c-layout-breadcrumbs-1 c-subtitle c-fonts-uppercase c-fonts-bold c-bordered c-bordered-both">
                <div class="container">
                    <div class="c-page-title c-pull-left">
                        <h3 class="c-font-uppercase c-font-sbold"><?php echo $this->translate('Customer Dashboard');?></h3>
                        <h4 class="">Page Sub Title Goes Here</h4>
                    </div>
                    <ul class="c-page-breadcrumbs c-theme-nav c-pull-right c-fonts-regular">
                        <li><a href="javascript:;" ng-click="changeTemplateURL('/ef-welcome');">Shop</a></li>
                        <li>/</li>
                        <li><a href="javascript:;"><?php echo $this->translate('Customer Dashboard');?></a></li>
                    </ul>
                </div>
            </div>
            <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="container" ng-controller="ProfileCtrl" ng-init="getProfile();">
				<?php echo $this->partial('shop/customer/leftmenu');?>
                <div class="c-layout-sidebar-content ">
                    <!-- BEGIN: PAGE CONTENT -->
                    <!-- BEGIN: CONTENT/SHOPS/SHOP-CUSTOMER-DASHBOARD-1 -->
                    <div class="c-content-title-1">
                        <h3 class="c-font-uppercase c-font-bold"><?php echo $this->translate('My Dashboard');?></h3>
                        <div class="c-line-left"></div>
                        <p class=""> <?php echo $this->translate('Hello');?>
                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-customer/profile',null,null,'sidebar-menu-shop-customer-profile');" class="c-theme-link">{{form.name}}</a> (<a href="<?php echo $this->url('logout',array(),array('force_canonical' => true)); ?>" class="c-theme-link"><?php echo $this->translate('not {{form.name}} ? Sign out');?></a>).
                            <br /> </p>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12 c-margin-b-20">
                            <h3 class="c-font-uppercase c-font-bold">{{form.name}}</h3>
                            <ul class="list-unstyled">
                                <li><?php echo $this->translate('Address');?>: {{form.address}}, {{form.address_city}}, {{form.address_country}}</li>
                                <li><?php echo $this->translate('Phone');?>: {{form.phone}}</li>
                                <li><?php echo $this->translate('Email');?>: {{form.email}}</li>
                            </ul>
                        </div>
                    </div>
                    <!-- END: CONTENT/SHOPS/SHOP-CUSTOMER-DASHBOARD-1 -->
                    <!-- END: PAGE CONTENT -->
                </div>
            </div>
