<?php if(isset($this->USER_LOGGED)){?>
<?php if($this->USER_LOGGED === true){?>
<div class="c-layout-sidebar-menu c-theme ">
	<!-- BEGIN: LAYOUT/SIDEBARS/SHOP-SIDEBAR-DASHBOARD -->
	<div class="c-sidebar-menu-toggler">
		<h3 class="c-title c-font-uppercase c-font-bold"><?php echo $this->translate('My Profile');?></h3>
		<a href="javascript:;" class="c-content-toggler">
			<span class="c-line"></span>
			<span class="c-line"></span>
			<span class="c-line"></span>
		</a>
	</div>
	<ul class="c-sidebar-menu collapse " id="sidebar-menu-1">
		<li class="c-dropdown c-open">
			<a href="javascript:;" class="c-toggler"><?php echo $this->translate('My Profile');?></a>
			<ul class="c-dropdown-menu">
				<li id="sidebar-menu-shop-customer-dashboard" class="c-active"><a href="javascript:;" ng-click="changeTemplateURL('/shop-customer/index',null,null,'sidebar-menu-shop-customer-dashboard');"><?php echo $this->translate('My Dashboard');?></a></li>
				<li id="sidebar-menu-shop-customer-profile" class=""><a href="javascript:;" ng-click="changeTemplateURL('/shop-customer/profile',null,null,'sidebar-menu-shop-customer-profile');"><?php echo $this->translate('Edit Profile');?></a></li>
				<li id="sidebar-menu-shop-customer-history" class=""><a href="javascript:;" ng-click="changeTemplateURL('/shop-customer/history',null,null,'sidebar-menu-shop-customer-history');"><?php echo $this->translate('Order History');?></a></li>
			</ul>
		</li>
	</ul>
	<!-- END: LAYOUT/SIDEBARS/SHOP-SIDEBAR-DASHBOARD -->
</div>
<?php }?>
<?php }?>