                <div class="c-layout-sidebar-menu c-theme ">
                    <!-- BEGIN: LAYOUT/SIDEBARS/SHOP-SIDEBAR-DASHBOARD -->
                    <div class="c-sidebar-menu-toggler">
                        <h3 class="c-title c-font-uppercase c-font-bold">My Profile</h3>
                        <a href="javascript:;" class="c-content-toggler">
                            <span class="c-line"></span>
                            <span class="c-line"></span>
                            <span class="c-line"></span>
                        </a>
                    </div>
                    <ul class="c-sidebar-menu collapse " id="sidebar-menu-1">
                        <li class="c-dropdown c-open">
                            <a href="javascript:;" class="c-toggler">My Profile</a>
                            <ul class="c-dropdown-menu">
                                <li class="c-active"><a href="javascript:;" ng-click="changeTemplateURL('/shop-customer/index');">My Dashbord</a></li>
                                <li class=""><a href="javascript:;" ng-click="changeTemplateURL('/shop-customer/profile');">Edit Profile</a></li>
                                <li class=""><a href="javascript:;" ng-click="changeTemplateURL('/shop-customer/history');">Order History</a></li>
                            </ul>
                        </li>
                    </ul>
                    <!-- END: LAYOUT/SIDEBARS/SHOP-SIDEBAR-DASHBOARD -->
                </div>