            <!-- BEGIN: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="c-layout-breadcrumbs-1 c-subtitle c-fonts-uppercase c-fonts-bold c-bordered c-bordered-both">
                <div class="container">
                    <div class="c-page-title c-pull-left">
                        <h3 class="c-font-uppercase c-font-sbold"><?php echo $this->translate('Customer Login/Register');?></h3>
                        <h4 class="">Page Sub Title Goes Here</h4>
                    </div>
                    <ul class="c-page-breadcrumbs c-theme-nav c-pull-right c-fonts-regular">
                        <li><a href="javascript:;" ng-click="changeTemplateURL('/ef-welcome');">Shop</a></li>
                        <li>/</li>
                        <li><a href="javascript:;"><?php echo $this->translate('Customer Edit Profile');?></a></li>
                    </ul>
                </div>
            </div>
            <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->            
            <div class="container" ng-controller="ProfileCtrl" ng-init="getProfile();">
            	<?php echo $this->partial('shop/customer/leftmenu');?>
                <div class="c-layout-sidebar-content ">
                    <!-- BEGIN: PAGE CONTENT -->
                    <div class="c-content-title-1">
                        <h3 class="c-font-uppercase c-font-bold"><?php echo $this->translate('Edit Profile');?></h3>
                        <div class="c-line-left"></div>
                    </div>
                    <form class="c-shop-form-1" name="profileForm" ng-submit="saveProfile()" novalidate>
                        <!-- BEGIN: ADDRESS FORM -->
                        <div class="">
                            <!-- BEGIN: BILLING ADDRESS -->
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="form-group col-md-6">
                                            <label class="control-label"><?php echo $this->translate('First Name');?></label>
                                            <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('First Name');?>" ng-model="form.firstname"> </div>
                                        <div class="col-md-6">
                                            <label class="control-label"><?php echo $this->translate('Last Name');?></label>
                                            <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Last Name');?>"  ng-model="form.lastname"> </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <label class="control-label"><?php echo $this->translate('Address');?></label>
                                    <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Street Address');?>"  ng-model="form.address"> </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Apartment, suite, unit etc. (optional)');?>"  ng-model="form.address_complement"> </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <label class="control-label"><?php echo $this->translate('Town / City');?></label>
                                    <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Town / City');?>"  ng-model="form.address_city"> </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="form-group col-md-6">
                                            <label class="control-label"><?php echo $this->translate('State / County');?></label>
                                            <select class="form-control c-square c-theme" ng-model="form.address_country" id="address_country">
                                                <option value=""><?php echo $this->translate('Select an option');?>...</option>
												<option value="<?php echo $this->translate('Brazil');?>"><?php echo $this->translate('Brazil');?></option>
		                                        <option value="<?php echo $this->translate('Singapore');?>"><?php echo $this->translate('Singapore');?></option>
		                                        <option value="<?php echo $this->translate('Indonesia');?>"><?php echo $this->translate('Indonesia');?></option>
		                                        <option value="<?php echo $this->translate('Thailand');?>"><?php echo $this->translate('Thailand');?></option>
		                                        <option value="<?php echo $this->translate('China');?>"><?php echo $this->translate('China');?></option>
                                            </select>
                                        </div>
                                        <div class="col-md-6">
                                            <label class="control-label"><?php echo $this->translate('Postcode / Zip');?></label>
                                            <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Postcode / Zip');?>"  ng-model="form.address_postcode"> </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="form-group col-md-6 has-error">
                                            <label class="control-label"><?php echo $this->translate('Email Address');?></label>
                                            <input type="email" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Email Address');?>" ng-model="form.email" required="required" > </div>
                                        <div class="col-md-6">
                                            <label class="control-label"><?php echo $this->translate('Phone');?></label>
                                            <input type="tel" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Phone');?>" ng-model="form.tel"> </div>
                                    </div>
                                </div>
                            </div>
                            <!-- END: BILLING ADDRESS -->
                            <!-- BEGIN: PASSWORD -->
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <label class="control-label"><?php echo $this->translate('Change Password');?></label>
                                    <input type="password" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Password');?>" ng-model="form.rpassword"> </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <label class="control-label"><?php echo $this->translate('Repeat Password');?></label>
                                    <input type="password" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Password');?>">
                                    <p class="help-block"><?php echo $this->translate('Hint: The password should be at least six characters long.');?>
                                        <br /><?php echo $this->translate('To make it stronger, use upper and lower case letters, numbers, and symbols like ! " ? $ % ^ & ).');?></p>
                                </div>
                            </div>
                            <!-- END: PASSWORD -->
                            <div class="row c-margin-t-30">
                                <div class="form-group col-md-12" role="group">
                                    <button type="submit" class="btn btn-lg c-theme-btn c-btn-square c-btn-uppercase c-btn-bold" ng-disabled="profileForm.$invalid"><?php echo $this->translate('Submit');?></button>
                                    <button type="button" class="btn btn-lg btn-default c-btn-square c-btn-uppercase c-btn-bold" ng-click="changeTemplateURL('/shop-customer/index',null,null,'sidebar-menu-shop-customer-dashboard');"><?php echo $this->translate('Cancel');?></button>
                                </div>
                            </div>
                        </div>
                        <!-- END: ADDRESS FORM -->
                    </form>
                    <!-- END: PAGE CONTENT -->
                </div>
            </div>
