            <!-- BEGIN: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="c-layout-breadcrumbs-1 c-subtitle c-fonts-uppercase c-fonts-bold c-bordered c-bordered-both">
                <div class="container">
                    <div class="c-page-title c-pull-left">
                        <h3 class="c-font-uppercase c-font-sbold"><?php echo $this->translate('Checkout');?></h3>
                        <h4 class="">Page Sub Title Goes Here</h4>
                    </div>
                    <ul class="c-page-breadcrumbs c-theme-nav c-pull-right c-fonts-regular">
                        <li><a href="javascript:;" ng-click="changeTemplateURL('/ef-welcome');"><?php echo $this->translate('Shop');?></a></li>
                        <li>/</li>
                        <li><a href="javascript:;"><?php echo $this->translate('Checkout');?></a></li>
                    </ul>
                </div>
            </div>
            <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <!-- BEGIN: PAGE CONTENT -->
            <div class="c-content-box c-size-lg">
                <div class="container">
                    <form class="c-shop-form-1">
                        <div class="row">
                            <!-- BEGIN: ADDRESS FORM -->
                            <div class="col-md-7 c-padding-20">
                                <!-- BEGIN: BILLING ADDRESS -->
                                <h3 class="c-font-bold c-font-uppercase c-font-24"><?php echo $this->translate('Billing Address');?></h3>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="form-group col-md-6">
                                                <label class="control-label"><?php echo $this->translate('First Name');?></label>
                                                <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('First Name');?>"> </div>
                                            <div class="col-md-6">
                                                <label class="control-label"><?php echo $this->translate('Last Name');?></label>
                                                <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Last Name');?>"> </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <label class="control-label"><?php echo $this->translate('Company Name');?></label>
                                        <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Company Name');?>"> </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <label class="control-label"><?php echo $this->translate('Address');?></label>
                                        <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Street Address');?>"> </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Apartment, suite, unit etc. (optional)');?>"> </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <label class="control-label"><?php echo $this->translate('Town / City');?></label>
                                        <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Town / City');?>"> </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="form-group col-md-6">
                                                    <label class="control-label"><?php echo $this->translate('State / County');?></label>
                                                <select class="form-control c-square c-theme" ng-model="form.country">
                                                    <option value="<?php echo $this->translate('Brazil');?>"><?php echo $this->translate('Brazil');?></option>
                                                    <option value="<?php echo $this->translate('Singapore');?>"><?php echo $this->translate('Singapore');?></option>
                                                    <option value="<?php echo $this->translate('Indonesia');?>"><?php echo $this->translate('Indonesia');?></option>
                                                    <option value="<?php echo $this->translate('Thailand');?>"><?php echo $this->translate('Thailand');?></option>
                                                    <option value="<?php echo $this->translate('China');?>"><?php echo $this->translate('China');?></option>
                                                </select>
                                            </div>
                                            <div class="col-md-6">
                                                <label class="control-label"><?php echo $this->translate('Postcode / Zip');?></label>
                                                <input type="text" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Postcode / Zip');?>"> </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <div class="row">
                                            <div class="form-group col-md-6">
                                                <label class="control-label"><?php echo $this->translate('Email Address');?></label>
                                                <input type="email" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Email Address');?>"> </div>
                                            <div class="col-md-6">
                                                <label class="control-label"><?php echo $this->translate('Phone');?></label>
                                                <input type="tel" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Phone');?>"> </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row c-margin-t-15">
                                    <div class="form-group col-md-12">
                                        <div class="c-checkbox c-toggle-hide" data-object-selector="c-account" data-animation-speed="600">
                                            <input type="checkbox" id="checkbox1-77" class="c-check" ng-model="form.checkbox">
                                            <label for="checkbox1-77">
                                                <span class="inc"></span>
                                                <span class="check"></span>
                                                <span class="box"></span> <?php echo $this->translate('Create an account?');?> </label>
                                        </div>
                                        <p class="help-block"><?php echo $this->translate('Create an account by entering the information below. If you are a returning customer please login.');?></p>
                                    </div>
                                </div>
                                <div class="row c-account" ng-show="form.checkbox">
                                    <div class="form-group col-md-12">
                                        <label class="control-label"><?php echo $this->translate('Account Password');?></label>
                                        <input type="password" class="form-control c-square c-theme" placeholder="<?php echo $this->translate('Password');?>"> </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <label class="control-label"><?php echo $this->translate('Order Notes');?></label>
                                        <textarea class="form-control c-square c-theme" rows="3" placeholder="<?php echo $this->translate('Note about your order, e.g. special notes for delivery.');?>"></textarea>
                                    </div>
                                </div>
                            </div>
                            <!-- END: ADDRESS FORM -->
                            <!-- BEGIN: ORDER FORM -->
                            <div class="col-md-5" ng-controller="ShopCartCtrl" ng-init="UpdateViewCart();">
                                <div class="c-content-bar-1 c-align-left c-bordered c-theme-border c-shadow">
                                    <h1 class="c-font-bold c-font-uppercase c-font-24"><?php echo $this->translate('Your Order');?></h1>
                                    <ul class="c-order list-unstyled">
                                        <li class="row c-margin-b-15">
                                            <div class="col-md-6 c-font-20">
                                                <h2><?php echo $this->translate('Product');?></h2>
                                            </div>
                                            <div class="col-md-6 c-font-20">
                                                <h2><?php echo $this->translate('Total');?></h2>
                                            </div>
                                        </li>
                                        <li class="row c-border-bottom"></li>
                                        <li class="row c-margin-b-15 c-margin-t-15" ng-repeat="(c_key, c_item) in cart">
                                            <div class="col-md-6 c-font-20"><a href="javascript:;" class="c-theme-link">{{c_item.form.name}}</a></div>
                                            <div class="col-md-6 c-font-20"><p class="">{{c_item.cart | currency}}</p></div>
                                        </li>
                                        <li class="row c-margin-b-15 c-margin-t-15">
                                            <div class="col-md-6 c-font-20"><?php echo $this->translate('Subtotal');?></div>
                                            <div class="col-md-6 c-font-20"><p class=""><span class="c-subtotal">{{subtotal | currency}}</span></p>
                                            </div>
                                        </li>
                                        <li class="row c-border-top c-margin-b-15"></li>
                                        <li class="row c-margin-b-15 c-margin-t-15">
                                            <div class="col-md-6 c-font-20"><p class="c-font-30"><?php echo $this->translate('Total');?></p></div>
                                            <div class="col-md-6 c-font-20"><p class="c-font-bold c-font-30"><span class="c-shipping-total">{{total | currency}}</span></p></div>
                                        </li>
                                        <li class="row">
                                            <div class="col-md-12">
                                                <div class="c-radio-list">
                                                    <div class="c-radio">
                                                        <input type="radio" id="radio1" class="c-radio" name="payment" checked="">
                                                        <label for="radio1" class="c-font-bold c-font-20">
                                                            <span class="inc"></span>
                                                            <span class="check"></span>
                                                            <span class="box"></span> <?php echo $this->translate('Direct Bank Transfer');?> </label>
                                                        <p class="help-block"><?php echo $this->translate('Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won\'t be shipped until the funds have cleared in our account.');?></p>
                                                    </div>
                                                    <div class="c-radio">
                                                        <input type="radio" id="radio3" class="c-radio" name="payment">
                                                        <label for="radio3" class="c-font-bold c-font-20">
                                                            <span class="inc"></span>
                                                            <span class="check"></span>
                                                            <span class="box"></span> <?php echo $this->translate('Paypal');?> </label>
                                                        <img class="img-responsive" width="250" src="https://www.paypalobjects.com/webstatic/mktg/Logo/AM_mc_vs_ms_ae_UK.png" /> </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="row c-margin-b-15 c-margin-t-15">
                                            <div class="form-group col-md-12">
                                                <div class="c-checkbox">
                                                    <input type="checkbox" id="checkbox1-11" class="c-check">
                                                    <label for="checkbox1-11">
                                                        <span class="inc"></span>
                                                        <span class="check"></span>
                                                        <span class="box"></span> <?php echo $this->translate('I\'ve read and accept the Terms & Conditions');?> </label>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="row">
                                            <div class="form-group col-md-12" role="group">
                                                <button type="button" ng-click="changeTemplateURL('/shop-checkout-complete');" class="btn btn-lg c-theme-btn c-btn-square c-btn-uppercase c-btn-bold"><?php echo $this->translate('Submit');?></button>
                                                <button type="button" ng-click="changeTemplateURL('/ef-welcome');" class="btn btn-lg btn-default c-btn-square c-btn-uppercase c-btn-bold"><?php echo $this->translate('Cancel');?></button>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <!-- END: ORDER FORM -->
                        </div>
                    </form>
                </div>
            </div>
            <!-- END: PAGE CONTENT -->