<?php 
use Zend\Console\Charset\Utf8;
$config = $this->SystemConfig;
$hostname = $project_host = isset($config['host'])?$config['host']:'https://ques.toledocom.net/';
$project_name = isset($config['name'])?$config['name']:'';
$project_mail = isset($config['support'])?$config['support']:'';
$linkhere='';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="format-detection" content="telephone=no"> 
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;">
<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />

<title><?php echo $project_name;?></title>

<style type="text/css">

	/* Some resets and issue fixes */
	#outlook a { padding:0; }
	body{ width:100% !important; -webkit-text; size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; }     
	.ReadMsgBody { width: 100%; }
	.ExternalClass {width:100%;} 
	.backgroundTable {margin:0 auto; padding:0; width:100%!important;} 
	table td {border-collapse: collapse;}
	.ExternalClass * {line-height: 115%;}           
	/* End reset */
	
	span.preheader{
		display: none;
		font-size: 1px;
		visibility: hidden;
		opacity: 0;
		color: transparent;
		height: 0;
		width: 0;
	}
	
    /* These are our tablet/medium screen media queries */
	@media screen and (max-width: 700px){

		/* Hide stuff */
		*[class="hide"] {display:none !important;}                             

		/* Centers content on mobile */
		*[class="center"] {text-align:center !important; width:100% !important; height:auto !important;}            

		/* 100percent width section with 20px padding */
		*[class="pad100"] {width:100% !important; padding:20px;} 

		/* 100percent width section with 20px padding left right */
		*[class="padleftright100"] {width:100% !important; padding:0 20px 0 20px;} 

		/* 100percent width section with 20px padding top bottom */
		*[class="padtopbottom100"] {width:100% !important; padding:20px 0px 20px 0px;} 
		
		/* 100percent width section with 20px padding top bottom */
		*[class="hr"] {width:300px !important;} 
		
		/* This sets elements to 100% width and fixes the height issues too, a god send */
		*[class="p5"] {width:5% !important; height:auto !important;} 
		
		*[class="p7"] {width:7% !important; height:auto !important;} 
		
		*[class="p10"] {width:10% !important; height:auto !important;} 
		
		*[class="p20"] {width:20% !important; height:auto !important;} 
		
		*[class="p30"] {width:30% !important; height:auto !important;} 
		
		*[class="p40"] {width:40% !important; height:auto !important;}
		
		*[class="p50"] {width:50% !important; height:auto !important;} 
		
		*[class="p60"] {width:60% !important; height:auto !important;}
		
		*[class="p70"] {width:70% !important; height:auto !important;}
		
		*[class="p80"] {width:80% !important; height:auto !important;}
		
		*[class="p90"] {width:90% !important; height:auto !important;}
		
		*[class="p100"] {width:100% !important; height:auto !important;}
		
		
		
		
		*[class="p15"] {width:15% !important; height:auto !important;} 
		
		*[class="p25"] {width:25% !important; height:auto !important;} 
		
		*[class="p35"] {width:35% !important; height:auto !important;} 
		
		*[class="p45"] {width:45% !important; height:auto !important;}
		
		*[class="p55"] {width:55% !important; height:auto !important;} 
		
		*[class="p65"] {width:65% !important; height:auto !important;}
		
		*[class="p75"] {width:75% !important; height:auto !important;}
		
		*[class="p85"] {width:85% !important; height:auto !important;}
		
		*[class="p87"] {width:87% !important; height:auto !important;}
		
		*[class="p93"] {width:93% !important; height:auto !important;}
		
		*[class="p95"] {width:95% !important; height:auto !important;}
		
		*[class="alignleft"] {text-align: left !important;}
		*[class="aligncenter"] {text-align: center !important;}
		
		*[class="button100"] {width:100% !important;}
		*[class="button90"] {width: 90% !important;}
		
		*[class="button70"] {width:70px !important;}
		*[class="button50"] {width:50px !important;}

	}

		</style>
</head>

<body style="padding:0; margin:0;">
<!-- ````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````|  Preheader |`````````````````````````````````````-->
<!-- ````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- PRE-HEADER TEXT Change this to text that should show up in mail client. -->
<span class="preheader" style="display: none !important; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;border-collapse: collapse;border: 0px;">
Ques, app para concursos e quizzes
</span>
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- ````````````````````````````````````````````|  End |`````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````|  Section 1 |``````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<table align="center" border="0" cellpadding="0" cellspacing="0" style="margin: 0; padding: 0;background: #cecece;" bgcolor="#cecece" width="100%">
   <tr>
      <td align="center" valign="top">
         <table align="center" width="800" border="0" cellspacing="0" cellpadding="0" class="p100" bgcolor="#fcfcfc" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
            <tr>
               <td align="center" valign="top">
                  <table border="0" cellpadding="0" cellspacing="0" class="p100" width="600" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;" >
                     <tr>
                        <td align="left" valign="top">
						<!--[if gte mso 9]>
                              <table align="left" border="0" cellpadding="0" cellspacing="0" width="600">
                                 <tr>
                                    <td align="left" valign="top" width="130">
                                       <![endif]-->
                           <table align="left"  border="0" cellpadding="0" cellspacing="0" width="128" class="p100" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                              <tr>
                                 <td valign="top" align="left">
                                    <table border="0" cellspacing="0" cellpadding="0" class="p100" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                                       <tr>
                                          <td valign="top" align="center">
                                             <table border="0" cellspacing="0" cellpadding="0" class="p100" align="center" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                                                <tr>
                                                   <td height="13" class="hide" style="font-size: 10px; line-height: 13px;">&nbsp;</td>
                                                </tr>
                                                <tr>
                                                   <td width="128" align="center">
                                                      <a href="<?php echo $linkhere; ?>" style="display: block; border-style: none !important; border: 0 !important;">
                                                      <img src="<?php echo $hostname;?>/img/logo.png" alt="Logo" border="0" style="display:block" />
                                                      </a>
                                                   </td>
                                                </tr>
                                                <tr>
                                                   <td height="13" class="hide" style="font-size: 10px; line-height: 13px;">&nbsp;</td>
                                                </tr>
                                             </table>
                                          </td>
                                       </tr>
                                    </table>
                                 </td>
                              </tr>
                           </table>
						   <!--[if gte mso 9]>
							</td>
							<td align="left" valign="top" width="470">
							<![endif]-->
						   <!--[if gte mso 9]>
							</td>
							</tr>
							</table>
							<![endif]-->
                        </td>
                     </tr>
                  </table>
               </td>
            </tr>
         </table>
      </td>
   </tr>
</table>
<!-- ````````````````````````````````````````````|  End |`````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````|  Section 2  |`````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<table align="center" border="0" cellpadding="0" cellspacing="0" style="margin: 0; padding: 0; background: #cecece;" bgcolor="#cecece" width="100%">
   <tr>
      <td align="center" valign="top">
         <table width="800" bgcolor="#fafafa" border="0" cellspacing="0" cellpadding="0" class="p100" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
            <tr>
               <td align="center" valign="top">
                  <div>
                     <table width="600" border="0" cellspacing="0" cellpadding="0" class="p80" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                        <tr>
                           <td valign="top">
                              <table border="0" cellspacing="0" cellpadding="0" width="600" class="p100" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                                 <tr>
                                    <td height="60"></td>
                                 </tr>
                                 <tr>
                                    <td align="center">
                                       <table border="0" align="center" cellpadding="0" cellspacing="0" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;border: 0px;" >
                                          <tr>
                                             <td align="center" style="color: #343434; font-size: 28px;">
                                                <font face="'Open Sans', sans-serif">
                                                <b><?php echo $title; ?></b>
                                                </font>
                                             </td>
                                          </tr>
                                       </table>
                                    </td>
                                 </tr>
                                 <tr>
                                    <td height="30"></td>
                                 </tr>
                                 <tr>
                                    <td align="center">
                                       <table border="0" align="center" cellpadding="0" cellspacing="0" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;border: 0px;" >
                                          <tr>
                                             <td align="center" style="color: #8d8d8d; font-size: 15px;line-height: 23px;">
                                                <font face="'Open Sans', sans-serif">
                                                <?php echo  $content;?>
                                                </font>
                                             </td>
                                          </tr>
                                       </table>
                                    </td>
                                 </tr>
                                 <tr>
                                    <td height="40"></td>
                                 </tr>
								 <tr>
                                    <td height="60"></td>
                                 </tr>
                              </table>
                           </td>
                        </tr>
                     </table>
                  </div>
               </td>
            </tr>
         </table>
      </td>
   </tr>
</table>


<!-- ````````````````````````````````````````````|  End |`````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````|  Footer 18  |`````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<table align="center" border="0" cellpadding="0" cellspacing="0" style="margin: 0; padding: 0; background: #cecece;" bgcolor="#cecece" width="100%">
   <tr>
      <td align="center" valign="top">
         <table width="800" bgcolor="#2f2f2f" border="0" cellspacing="0" cellpadding="0" class="p100" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
            <tr>
               <td align="center" valign="top">
                  <div>
                     <table width="600" border="0" cellspacing="0" cellpadding="0" class="p100" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                        <tr>
                           <td valign="top">
                              <table border="0" align="center" cellspacing="0" cellpadding="0" width="600" class="p80" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                                 <tr>
                                    <td valign="top">
                                       <table border="0" cellspacing="0" cellpadding="0" width="600" class="p100" style="mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                                          <tr>
                                             <td height="50"></td>
                                          </tr>
                                          <tr>
                                             <td height="30"></td>
                                          </tr>
                                          <tr>
                                             <td align="center">
                                                <table border="0" align="center" cellpadding="0" cellspacing="0" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;border: 0px;" >
                                                   <tr>
                                                      <td align="center" style="color: #8d8d8d; font-size: 15px;line-height: 23px;">
                                                         <font face="'Open Sans', sans-serif">
                                                         Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis maecenas lectus.
                                                         </font>
                                                      </td>
                                                   </tr>
                                                </table>
                                             </td>
                                          </tr>
                                       </table>
                                    </td>
                                 </tr>
                                 <tr>
                                    <td height="30"></td>
                                 </tr>
                                 <tr>
                                    <td align="center">
                                    </td>
                                 </tr>
                                 <tr>
                                    <td align="center">
                                       <table border="0" align="center" cellpadding="0" cellspacing="0" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;border: 0px;" >
                                          <tr>
                                             <td align="center" style="color: #acacac; font-size: 12px;line-height: 18px;">
                                                <font face="'Open Sans', sans-serif">
                                                Copyright YONICemail 2015, Area Name, State, Country.
                                                </font>
                                             </td>
                                          </tr>
                                       </table>
                                    </td>
                                 </tr>
                                 <tr>
                                    <td height="30"></td>
                                 </tr>
                                 <tr>
                                    <td height="50"></td>
                                 </tr>
                              </table>
                           </td>
                        </tr>
                     </table>
                  </div>
               </td>
            </tr>
         </table>
      </td>
   </tr>
</table>
<!-- ````````````````````````````````````````````|  End |`````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
<!-- `````````````````````````````````````````````````````````````````````````````````````````````-->
</body>
</html>