<?php echo $this->partial('shop/products/breadcrumbs'); ?>
    <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
    <div class="container">
        <?php echo $this->partial('shop/projects/leftmenu'); ?>
        <div class="c-layout-sidebar-content ">
            <!-- BEGIN C-LAYOUT-SIDEBAR-CONTENT-->
            <div class="" ng-controller="ProductsCtrl" ng-init="getProducts();">
                <div class="portlet">
                    <div class="portlet-title">
                        <div class="caption">
                            <div class="pull-right" ng-show="form.id > 0"># {{form.id}}</div>
                        </div>
                    </div>
                    <!-- BEGIN FORM -->
                    <div class="portlet-body form" ng-show="screen_from">
                        <form class="form-horizontal" role="form" name="formProducts">
                            <input type="text" ng-show="false" id="accepted_file" value=".zip"/>
                            <div class="form-group margin-top-40" style="margin-bottom: -20px;">
                                <label
                                    class="col-md-7 uppercase bold"><?php echo $this->translate('PROJECT'); ?></label>
                            </div>

                            <hr/>

                            <!-- PROJETCS -->
                            <div class="form-group margin-top-40">
                                <label class="col-md-2 control-label bold pull-left">
                                    <small><?php echo $this->translate('Family Name'); ?></small>
                                </label>
                                <div class="col-md-10">
                                    <input type="text" ng-model="form.name" class="form-control" maxlength="255"
                                           placeholder="<?php echo $this->translate('PROJECT NAME'); ?>"
                                           required="required" ng-blur="addFamilyItem();"/>
                                </div>
                            </div>

                            <!-- LICENCES -->
                            <div class="form-group margin-top-40">
                                <label class="col-md-2 control-label bold pull-left">
                                    <small><?php echo $this->translate('Lincese'); ?> </small>
                                </label>
                                <div class="col-md-10">
                                    <ul class="list-group">
                                        <li ng-repeat="(l_key, l_item) in licenses" class="checkbox-inline"
                                            style="padding-left: 0px">
                                            <div ng-init="setLicenseId(l_key, l_item.id)">
                                                <div class="c-checkbox c-toggle-hide"
                                                     data-object-selector="c-form-register" data-animation-speed="600">
                                                    <input type="checkbox" id="checkbox-{{l_key}}" class="c-check"
                                                           ng-model="form.licenses[l_key].check_enabled">
                                                    <label for="checkbox-{{l_key}}"><span class="inc"></span><span
                                                            class="check"></span><span class="box"></span>
                                                        <small
                                                            ng-class="form.licenses[l_key].check_enabled?'c-font-green':'c-font-red'">
                                                            {{l_item.name}}
                                                        </small>
                                                    </label>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>


                            <!-- FAMILY -->
                            <section ng-repeat="(f_key, f_item) in families">
                                <!-- FORMATS -->
                                <hr/>
                                <input type="text" ng-show="false" ng-model="f_item.family_name=form.name" />
                                <!-- PRICES -->
                                <div class="form-group margin-top-40">
                                    <label class="col-md-2 control-label bold pull-left">
                                        <small><?php echo $this->translate('Prices'); ?> </small>
                                    </label>

                                    <div class="col-md-10">
                                        <label class="checkbox-inline control-label small">
                                            <?php echo $this->translate('Weight'); ?>&nbsp;
                                            <input
                                                ng-change="updateWeight(f_key, l_key, l_item.id);"
                                                ng-model="f_item.money_weight"
                                                ui-money-mask="2"
                                                type="text" size="8"></label>
                                        <label class="checkbox-inline control-label small">
                                            <?php echo $this->translate('Family'); ?>&nbsp;
                                            <input
                                                ui-money-mask="2"
                                                ng-model="f_item.money_family"
                                                type="text" size="8"></label>
                                    </div>

                                </div>

                                <section ng-repeat="(t_key, t_item) in formats" id="sec-formats"
                                         ng-init="f_item.formats[t_item.id].format_id = t_item.id">
                                    <!-- UPLOAD -->
                                    <div class="form-group margin-top-40">
                                        <label class="col-md-2 control-label bold pull-left"><a
                                                ng-show="f_item.formats[t_item.id].number_files" href="javascript:;"
                                                class="btn c-btn btn-xs" ng-model="f_item.formats[t_item.id].collapsed"
                                                ng-click="f_item.formats[t_item.id].collapsed=!f_item.formats[t_item.id].collapsed"><i
                                                    class="fa"
                                                    ng-class="f_item.formats[t_item.id].collapsed?'fa-minus':'fa-plus'"></i></a>
                                            {{t_item.name}}</label>
                                        <div class="col-md-8">
                                            <div class="input-group">
                                                <!-- readonly="readonly"  -->
                                                <input type="text" placeholder="" readonly="readonly"
                                                       class="form-control"
                                                       ng-model="f_item.formats[t_item.id].media_url"
                                                       id="media_url{{f_key}}{{t_key}}"
                                                       name="media_url{{f_key}}{{t_key}}"
                                                       ng-change="getRetrieveDetails(f_key, t_key ,t_item.id);"/>
                                                <span class="input-group-btn">
                                                    <button class="btn blue" type="button"
                                                            data-uuid="{{t_item.id}}"
                                                            data-id="media_url{{f_key}}{{t_key}}"
                                                            onclick="fileUploadDropzone($(this).data('id'), $(this).data('uuid'));"><?php echo $this->translate('Upload'); ?></button></span>
                                            </div>
                                        </div>
                                        <div class="col-md-2 pull-right">
                                            <label class="control-label bold"><i class="fa"
                                                                                 ng-class="f_item.formats[t_item.id].number_files?'fa-check':'fa-close'"></i>&nbsp;&nbsp;
                                                {{f_item.formats[t_item.id].number_files || 0 }}
                                                &nbsp;&nbsp;<?php echo $this->translate('FILES'); ?></label>
                                        </div>
                                    </div>
                                    <!-- ITEMS -->
                                    <div class="form-group margin-top-40" ng-show="f_item.formats[t_item.id].collapsed">
                                        <div class="col-md-12">
                                            <table class="table table-bordered table-striped">
                                                <tr ng-repeat="(fl_key, fl_item) in f_item.formats[t_item.id].files">
                                                    <td class="col-md-3 small bold">{{fl_item.font_file}}</td>
                                                    <td class="col-md-6"><span ng-show="t_item.id == '0'">{{fl_item.font_subfamily}}</span><input
                                                            ng-hide="t_item.id == '0'" type="text" class="form-control"
                                                            ng-model="fl_item.font_subfamily"/></td>
                                                    <td class="col-md-2"><span ng-show="t_item.id == '0'">Trial</span>
                                                        <div ng-hide="t_item.id == '0'" class="input-group"><span
                                                                class="input-group-addon"><input type="checkbox"
                                                                                                 ng-model="fl_item.check_price"></span><input
                                                                ui-money-mask="2" ng-model="fl_item.font_price"
                                                                type="text" class="form-control"
                                                                ng-disabled="!fl_item.check_price"></div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </section>
                            </section>
                            <!-- BUTTON -->
                            <hr/>
                            <div class="form-group margin-top-40 margin-bottom-10">
                                <div class="col-md-12 uppercase bold">
                                    <a href="javascript:;"
                                       class="btn c-btn btn-lg c-btn-green c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-l pull-right"
                                       ng-click="goSummary();" ng-hide="formProducts.$invalid"
                                       ng-disabled="formProducts.$invalid"><?php echo $this->translate('Next'); ?> </a>
                                    <a href="javascript:;"
                                       class="btn c-btn btn-lg c-btn-red c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-l pull-left"
                                       ng-click="goBack('<?php echo $this->translate('GO BACK'); ?>', '<?php echo $this->translate('No'); ?>', '<?php echo $this->translate('Are you sure?'); ?>', '<?php echo $this->translate('All unsaved data will be lost.'); ?>', '<?php echo $this->translate('Error'); ?>');"><?php echo $this->translate('Go Back'); ?></a>
                                </div>
                            </div>
                    </div>
                    </form>
                </div>
                <!-- END FORM -->

                <!-- BEGIN CONFIRM -->
                <div class="portlet-body form" ng-show="screen_summary">
                    <div class="col-md-12">
                        <form class="form-horizontal" role="form" name="formSummary">
                            <div class="form-group margin-top-40 margin-bottom-20">
                                <label
                                    class="uppercase c-font-bold bold pull-left"><?php echo $this->translate('PROJECT'); ?></label>
                                <label
                                    class="uppercase c-font-bold bold pull-right c-font-red"><?php echo $this->translate('SUMMARY'); ?></label>
                            </div>

                            <!-- PROJECT INFO -->
                            <hr class="row"/>
                            <div class="form-group margin-top-40 margin-bottom-20">
                                <!-- PROJECT -->
                                <div class="col-md-12">
                                    <label class="pull-left"><strong><?php echo $this->translate('Family Name'); ?>
                                            :</strong> <span>{{form.name}}</span></label>
                                    <!--<label class="pull-right">{{families.length}}
                                        <span> <?php /* echo $this->translate('Family'); */ ?> </span></label>-->
                                </div>

                                <!-- LICENSES -->
                                <div class="col-md-12">
                                    <label class="pull-left"><strong><?php echo $this->translate('Licenses'); ?>
                                            :&nbsp;</strong>
                                                <span ng-repeat="(l_key, l_item) in licenses"
                                                    ng-show="form.licenses[l_key].check_enabled"
                                                    class="checkbox-inline"
                                                    style="padding-left: 0px">
                                                    <span>{{l_item.name}}&nbsp;&nbsp;</span>
                                                </span>
                                        </label>
                                </div>

                            </div>

                            <!-- FAMILIES -->
                            <section ng-repeat="(f_key, f_item) in families">
                                <!-- FAMILY -->
                                <hr class="row"/>
                                <div class="form-group margin-top-40 margin-bottom-20">

                                    <div class="col-md-2 pull-left">
                                        <label class="pull-left"><strong><?php echo $this->translate('Prices'); ?>
                                                :</strong></label>
                                    </div>
                                    <div class="col-md-8 pull-left" >
                                        <table class="table" >
                                            <!-- HEADER -->
                                            <tr class="not-not-border">
                                                <td class="not-not-border" ><label class="control-label">
                                                        <small><?php echo $this->translate('WEIGHT'); ?></small>
                                                    </label></td>
                                                <td class="not-not-border" ><label class="control-label">
                                                        <small><?php echo $this->translate('FAMILY'); ?></small>
                                                    </label></td>
                                            </tr>
                                            <!-- PRICES -->
                                            <tr>
                                                <td class="not-not-border">
                                                    <small> {{f_item.money_weight | currency}}</small>
                                                </td>
                                                <td class="not-not-border">
                                                    <small> {{f_item.money_family | currency}}</small>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!--<div class="col-md-6 pull-left">
                                        <label class="control-label"><a href="javascript:;"
                                                                        class="btn-xs btn btn-danger c-btn-circle">
                                                {{f_key + 1}} </a>
                                            <small class="c-font-bold"><?php /* echo $this->translate('Family Name'); */ ?>
                                                :
                                            </small>
                                            <small> {{f_item.family_name}}</small>
                                        </label>
                                    </div>-->

                                </div>
                                <!-- FORMATS -->
                                <div class="form-group margin-top-40 margin-bottom-20">
                                    <section ng-repeat="(t_key, t_item) in formats" id="sec-formats">
                                        <div class="col-md-6">
                                            <hr class="row"/>
                                            <h5>{{t_item.name}}</h5>
                                            <table class="table table-bordered table-striped"
                                            ">
                                            <tr ng-repeat="(fl_key, fl_item) in f_item.formats[t_item.id].files"
                                                ng-show="f_item.formats[t_item.id].files">
                                                <td class="not-not-border">{{fl_item.font_subfamily}}</td>
                                                <td class="not-not-border"><span ng-show="t_item.id == '0'">Trial</span><span
                                                        ng-hide="t_item.id == '0'">{{fl_item.font_price | currency}}
                                                </td>
                                            </tr>
                                            <tr ng-hide="f_item.formats[t_item.id].files">
                                                <td colspan="2">
                                                    <small
                                                        class="c-font-red"><?php echo $this->translate('No file uploaded'); ?></small>
                                                </td>
                                            </tr>
                                            </table>
                                        </div>
                                    </section>
                                </div>
                            </section>
                            <!-- BUTTON -->
                            <hr class="row"/>
                            <div class="form-group margin-top-40 margin-bottom-10">
                                <div class="col-md-12 uppercase bold">
                                    <a href="javascript:;"
                                       class="btn c-btn btn-lg c-btn-red c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-l pull-right"
                                       ng-click="saveProducts();"><?php echo $this->translate('Finish'); ?> </a>
                                    <a href="javascript:;"
                                       class="btn c-btn btn-lg c-btn-grey-3 c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-l pull-left"
                                       ng-click="goForm();"><?php echo $this->translate('Edit'); ?></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END CONFIRM -->

            </div>
        </div>
        <!-- END C-LAYOUT-SIDEBAR-CONTENT-->
    </div>
    </div>

<?php echo $this->partial('file-upload-form-static'); ?>