<?php echo $this->partial('shop/licenses/breadcrumbs'); ?>
    <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
    <div class="container">
        <?php echo $this->partial('shop/projects/leftmenu'); ?>
        <div class="c-layout-sidebar-content ">
            <!-- BEGIN C-LAYOUT-SIDEBAR-CONTENT-->
            <div class="" ng-controller="LicensesCtrl" ng-init="getLicenses();">
                <div class="portlet">
                    <div class="portlet-title">
                        <div class="caption">
                            <div class="pull-right" ng-show="form.id > 0"># {{form.id}}</div>
                        </div>
                    </div>
                    <!-- BEGIN BODY -->
                    <div class="portlet-body form">
                        <form class="form-horizontal" role="form" name="formLicenses">
                            <div class="form-group margin-top-40 " style="margin-bottom: -20px">
                                <label
                                    class="col-md-7 uppercase bold"><?php echo $this->translate('LICENSE'); ?></label>
                            </div>

                            <hr/>

                            <!-- NAME -->
                            <div class="form-group margin-top-40">
                                <label
                                    class="col-md-1 control-label bold pull-left"><?php echo $this->translate('Name'); ?></label>
                                <div class="col-md-6">
                                    <input type="text" ng-model="form.name" class="form-control text-danger"
                                           maxlength="255"
                                           placeholder="<?php echo $this->translate('Trial, Project, Classic, OEM ...'); ?>"
                                           required="required"/>
                                </div>

                                <div class="col-md-5">
                                    <div class="">
                                        <div class="input-group">
                                            <input type="text" placeholder="" readonly="readonly" class="form-control"
                                                   ng-model="form.media_url" id="media_url" name="media_url"
                                                   style="width: 230px"/>

                                            <span class="input-group-btn " style=""><button class="btn blue"
                                                                                            type="button"
                                                                                            onclick="fileUploadDropzone('media_url');"><?php echo $this->translate('Upload'); ?></button></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- FONTS FILES -->
                            <div class="form-group margin-bottom-20">
                                <label
                                    class="col-md-1 control-label bold pull-left"><?php echo $this->translate('Files'); ?>
                                </label>
                                <div class="col-md-6">
                                    <label class="checkbox-inline control-label"
                                           ng-show="companyData.check_fmt_otf">
                                            <input type="checkbox"
                                                  ng-model="form.check_fmt_otf"
                                                  id="check_otf"><?php echo $this->translate('.OTF'); ?>
                                    </label>
                                    <label class="checkbox-inline control-label"
                                           ng-show="companyData.check_fmt_ttf">
                                            <input type="checkbox"
                                              ng-model="form.check_fmt_ttf"
                                              id="check_ttf"><?php echo $this->translate('.TTF'); ?>
                                    </label>
                                    <label class="checkbox-inline control-label"
                                           ng-show="companyData.check_fmt_eot">
                                            <input type="checkbox"
                                              ng-model="form.check_fmt_eot"
                                              id="check_eot"><?php echo $this->translate('.EOT'); ?>
                                    </label>
                                    <label class="checkbox-inline control-label"
                                           ng-show="companyData.check_fmt_woff">
                                            <input type="checkbox"
                                               ng-model="form.check_fmt_woff"
                                               id="check_woff"><?php echo $this->translate('.WOFF'); ?>
                                    </label>
                                    <label class="checkbox-inline control-label"
                                           ng-show="companyData.check_fmt_woff2">
                                            <input type="checkbox"
                                            ng-model="form.check_fmt_woff2"
                                            id="check_woff2"><?php echo $this->translate('.WOFF2'); ?>
                                    </label>


                                </div>

                                <div class="col-md-4">
                                    <label class="checkbox-inline control-label"
                                           ng-show="companyData.check_fmt_trial">
                                            <input type="checkbox"
                                                ng-model="form.check_fmt_trial"
                                                id="check_trial"><?php echo $this->translate('Trial'); ?>
                                    </label>
                                </div>
                            </div>


                            <!-- ACTIVATION -->
                            <div class="form-group margin-bottom-20">
                                <label
                                    class="col-md-1 control-label bold pull-left"><?php echo $this->translate('Activate'); ?>
                                </label>
                                <div class="col-md-10">
                                    <label class="checkbox-inline control-label">
                                        <input type="checkbox"
                                               ng-model="form.check_enabled"
                                               id="check_enabled"></label>
                                </div>
                            </div>

                            <!-- INFO -->
                            <div class="form-group margin-top-40" style="margin-top: 40px; margin-bottom: -20px;">
                                <label
                                    class="col-md-9 uppercase bold"
                                    style=" vertical-align: text-bottom; margin-top: 18px;"><?php echo $this->translate('LICENSE INFO'); ?></label>

                                <div class="col-md-1 form-group pull-right" style="margin-right: 20px;"><a
                                            ng-click="addFormatItem(4);" href="javascript:;"
                                        class="btn c-btn c-btn-green c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-l"><i
                                            class="fa fa-plus"></i></a></div>

                            </div>

                            <hr/>

                            <div class="form-group margin-top-10">

                                <div class="col-md-11">
                                    <div class="input-group col-md-10 pull-left">
                                        <ul class="list-unstyled" ui-sortable="sortableFormatDesktop"
                                            ng-model="form.formats[4]">
                                            <li ng-repeat="(cart_key, cart_item) in form.formats[4]"
                                                class="col-md-12">
                                                <p>
                                                <table>
                                                    <tr>
                                                        <td class="col-md-7">
                                                            <input type="text" class="form-control"
                                                                ng-model="cart_item.parameters"
                                                                placeholder="<?php echo $this->translate('1-2 USERS, UNLIMITED'); ?>">
                                                        </td>
                                                        <td class="col-md-3">
                                                            <input type="text" only-number
                                                                class="form-control"
                                                                ng-model="cart_item.multiplier"
                                                                placeholder="<?php echo $this->translate('Multiplier'); ?>">
                                                        </td>
                                                        <td class="col-md-2">
                                                            <span class="input-group-btn">
                                                                <div class="btn c-btn c-btn-yellow c-btn-square c-font-white myHandle">{{cart_key}}</div>
                                                            </span>
                                                            <span class="input-group-btn"><button
                                                                    class="btn c-btn c-btn-red c-btn-square c-font-white"
                                                                    type="button"
                                                                    ng-click="removeFormatItem(4, cart_key)"><i class="fa fa-minus"></i></button></span>
                                                        </td>
                                                    </tr>
                                                </table>
                                                </p>
                                            </li>
                                        </ul>
                                    </div>

                                </div>
                            </div>

                            <!-- BUTTON -->
                            <hr class="row"/>
                            <div class="form-group margin-top-40 margin-bottom-10">
                                <div class="col-md-12 uppercase bold">
                                    <a href="javascript:;"
                                       class="pull-right btn c-btn btn-lg c-btn-green c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-l"
                                       ng-click="saveLicenses();"
                                       ng-disabled="formLicenses.$invalid"><?php echo $this->translate('Save'); ?> </a>
                                    <a href="javascript:;"
                                       class="pull-left btn c-btn btn-lg c-btn-red c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-l"
                                       ng-click="changeTemplateURL('/ef-licenses');"><?php echo $this->translate('Go Back'); ?></a>
                                </div>
                            </div>
                    </div>
                    </form>
                </div>
                <!-- END BODY -->
            </div>
        </div>
        <!-- END C-LAYOUT-SIDEBAR-CONTENT-->
    </div>
    </div>

<?php echo $this->partial('file-upload-form-static'); ?>