                    <div class="row">
                        <div class="col-md-3 col-sm-6 c-margin-b-20">
                            <div class="c-content-product-2 c-bg-white">
                                <div class="c-content-overlay">
                                    
                                    <div class="c-label c-label-right c-theme-bg c-font-uppercase c-font-white c-font-13 c-font-bold">New</div>
                                    <div class="c-overlay-wrapper">
                                        <div class="c-overlay-content">
                                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                                        </div>
                                    </div>
                                    <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px; background-image: url('http://placehold.it/1200x900');"></div>
                                </div>
                                <div class="c-info">
                                    <p class="c-title c-font-18 c-font-slim">Acumin</p>
                                    <p class="c-price c-font-16 c-font-slim">$548 &nbsp;
                                        
                                    </p>
                                </div>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Qana</a>
                                    </div>
                                    <div class="btn-group c-border-left c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 c-margin-b-20">
                            <div class="c-content-product-2 c-bg-white">
                                <div class="c-content-overlay">
                                    <div class="c-overlay-wrapper">
                                        <div class="c-overlay-content">
                                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                                        </div>
                                    </div>
                                    <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px; background-image: url('http://placehold.it/1200x900');"></div>
                                </div>
                                <div class="c-info">
                                    <p class="c-title c-font-18 c-font-slim">Litania </p>
                                    <p class="c-price c-font-16 c-font-slim">$548 &nbsp;
                                        
                                    </p>
                                </div>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">MMGV</a>
                                    </div>
                                    <div class="btn-group c-border-left c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 c-margin-b-20">
                            <div class="c-content-product-2 c-bg-white">
                                <div class="c-content-overlay">
                                    <div class="c-overlay-wrapper">
                                        <div class="c-overlay-content">
                                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                                        </div>
                                    </div>
                                    <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px; background-image: url('http://placehold.it/1200x900');"></div>
                                </div>
                                <div class="c-info">
                                    <p class="c-title c-font-18 c-font-slim">Blenny </p>
                                    <p class="c-price c-font-16 c-font-slim">$548 &nbsp;
                                        
                                    </p>
                                </div>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">User C</a>
                                    </div>
                                    <div class="btn-group c-border-left c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 c-margin-b-20">
                            <div class="c-content-product-2 c-bg-white">
                                <div class="c-content-overlay">
                                    <div class="c-label c-theme-bg c-font-uppercase c-font-white c-font-13 c-font-bold">New</div>
                                    <div class="c-overlay-wrapper">
                                        <div class="c-overlay-content">
                                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                                        </div>
                                    </div>
                                    <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px; background-image: url('http://placehold.it/1200x900');"></div>
                                </div>
                                <div class="c-info">
                                    <p class="c-title c-font-18 c-font-slim">Chaparral Pro</p>
                                    <p class="c-price c-font-16 c-font-slim">$548 &nbsp;
                                        
                                    </p>
                                </div>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">User B</a>
                                    </div>
                                    <div class="btn-group c-border-left c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 col-sm-6 c-margin-b-20">
                            <div class="c-content-product-2 c-bg-white">
                                <div class="c-content-overlay">
                                    
                                    <div class="c-overlay-wrapper">
                                        <div class="c-overlay-content">
                                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                                        </div>
                                    </div>
                                    <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px; background-image: url(http://placehold.it/1200x900);"></div>
                                </div>
                                <div class="c-info">
                                    <p class="c-title c-font-18 c-font-slim">Watches</p>
                                    <p class="c-price c-font-16 c-font-slim">$548 &nbsp;
                                        
                                    </p>
                                </div>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">User A</a>
                                    </div>
                                    <div class="btn-group c-border-left c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 c-margin-b-20">
                            <div class="c-content-product-2 c-bg-white">
                                <div class="c-content-overlay">
                                    <div class="c-overlay-wrapper">
                                        <div class="c-overlay-content">
                                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                                        </div>
                                    </div>
                                    <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px; background-image: url('http://placehold.it/1200x900');"></div>
                                </div>
                                <div class="c-info">
                                    <p class="c-title c-font-18 c-font-slim">Exclusive</p>
                                    <p class="c-price c-font-16 c-font-slim">$548 &nbsp;
                                        
                                    </p>
                                </div>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Studio B</a>
                                    </div>
                                    <div class="btn-group c-border-left c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 c-margin-b-20">
                            <div class="c-content-product-2 c-bg-white">
                                <div class="c-content-overlay">
                                    <div class="c-overlay-wrapper">
                                        <div class="c-overlay-content">
                                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                                        </div>
                                    </div>
                                    <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px; background-image: url('http://placehold.it/1200x900');"></div>
                                </div>
                                <div class="c-info">
                                    <p class="c-title c-font-18 c-font-slim">Master</p>
                                    <p class="c-price c-font-16 c-font-slim">$548 &nbsp;
                                        
                                    </p>
                                </div>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Studio A</a>
                                    </div>
                                    <div class="btn-group c-border-left c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 c-margin-b-20">
                            <div class="c-content-product-2 c-bg-white">
                                <div class="c-content-overlay">
                                    <div class="c-label c-theme-bg c-font-uppercase c-font-white c-font-13 c-font-bold">New</div>
                                    <div class="c-overlay-wrapper">
                                        <div class="c-overlay-content">
                                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                                        </div>
                                    </div>
                                    <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px; background-image: url('http://placehold.it/1200x900');"></div>
                                </div>
                                <div class="c-info">
                                    <p class="c-title c-font-18 c-font-slim">Mobile</p>
                                    <p class="c-price c-font-16 c-font-slim">$548 &nbsp;
                                        
                                    </p>
                                </div>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Studio Z</a>
                                    </div>
                                    <div class="btn-group c-border-left c-border-top" role="group">
                                        <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>