<div class="copyright">
	 <?php echo $this->partial('copyright');?>
</div>
<!-- END LOGIN -->
<!--[if lt IE 9]>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/respond.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<!-- BEGIN CORE PLUGINS -->
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/assets/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="<?php echo $this->basePath(); ?>/assets/global/scripts/app.min.js" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN ANGULAR JS -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular/angular.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-i18n/angular-locale_pt-br.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/ngstorage/ngStorage.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-sanitize/angular-sanitize.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-google-places-autocomplete/src/autocomplete.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/ng-file-upload/ng-file-upload.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-ui-select2/src/select2.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-ui-sortable/sortable.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/video.js/dist/video.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-ipsum/dist/ipsum.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-bootstrap-switch/dist/angular-bootstrap-switch.min.js"></script>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/functions.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/message.js"></script>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/app/app.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/app/controllers/ForgetCtrl.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/app/controllers/LoginCtrl.js"></script>
<!-- END ANGULAR JS -->
<!-- END THEME LAYOUT SCRIPTS -->
</body>
<!-- END BODY -->
</html>