<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" ng-app="QuizApp">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>E-Font Shop</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="efonts, shop, fonts, web, desktop, mobile" name="description"/>
<meta content="calraiden" name="author"/>

<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700&amp;subset=all' rel='stylesheet' type='text/css'>
<link href="<?php echo $this->basePath(); ?>/assets/plugins/socicon/socicon.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/bootstrap-social/bootstrap-social.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/animate/animate.min.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN: BASE PLUGINS  -->
<link href="<?php echo $this->basePath(); ?>/assets/plugins/revo-slider/css/settings.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/revo-slider/css/layers.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/revo-slider/css/navigation.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/cubeportfolio/css/cubeportfolio.min.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/owl-carousel/owl.carousel.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/owl-carousel/owl.theme.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/owl-carousel/owl.transitions.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/fancybox/jquery.fancybox.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/plugins/slider-for-bootstrap/css/slider.css" rel="stylesheet" type="text/css" />
<!-- END: BASE PLUGINS -->
<!-- BEGIN THEME STYLES -->
<link href="<?php echo $this->basePath(); ?>/assets/base/css/plugins.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/base/css/components.css" id="style_components" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/base/css/themes/default.css" rel="stylesheet" id="style_theme" type="text/css" />
<link href="<?php echo $this->basePath(); ?>/assets/base/css/custom.css" rel="stylesheet" type="text/css" />
<!-- END THEME STYLES -->
<!-- BOWER -->
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/bower_components/animate.css/animate.min.css">
<!-- END BOWER -->
<!-- BEGIN CUSTOM -->
<link href="<?php echo $this->basePath(); ?>/css/spinners.css" rel="stylesheet">
<link href="<?php echo $this->basePath(); ?>/css/style.css" rel="stylesheet">
<!-- END CUSTOME -->
<?php echo $this->partial('metatags');?>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGO -->
<div class="logo">
	<a href="javascript:;">
	<img src="<?php echo $this->basePath(); ?>/img/logo.png" alt=""/>
	</a>
</div>
<!-- END LOGO -->