<?php
$filename = $this->download;
if (file_exists ( $filename )) {
	// send $filename to browser
	$finfo = finfo_open ( FILEINFO_MIME_TYPE );
	$mimeType = finfo_file ( $finfo, $filename );
	$size = filesize ( $filename );
	$name = basename ( $filename );
	
	if (isset ( $_SERVER ['HTTPS'] ) && $_SERVER ['HTTPS'] == 'on') {
		// cache settings for IE6 on HTTPS
		header ( 'Cache-Control: max-age=120' );
		header ( 'Pragma: public' );
	} else {
		header ( 'Cache-Control: private, max-age=120, must-revalidate' );
		header ( "Pragma: no-cache" );
	}
	header ( "Expires: Sat, 26 Jul ".(date('Y')+1)." 05:00:00 GMT" ); // long ago
	header ( "Content-Type: $mimeType" );
	header ( 'Content-Disposition: attachment; filename="' . $name . '";' );
	header ( "Accept-Ranges: bytes" );
	header ( 'Content-Length: ' . filesize ( $filename ) );
	
	print readfile ( $filename );
}
exit ();