<meta content="calraiden" name="author" />
<meta name="description" content="E-Font Shop." />
<meta name="keywords" content="efont, fonts, litters, web, desktop, apps, mobile" />
<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="E-Font Shop">
<meta itemprop="description" content="efont, fonts, litters, web, desktop, apps, mobile">
<!-- Twitter Card data -->
<meta name="twitter:card" content="product">
<meta name="twitter:site" content="@publisher_handle">
<meta name="twitter:title" content="E-Font Shop">
<meta name="twitter:description" content="efont, fonts, litters, web, desktop, apps, mobile">
<meta name="twitter:creator" content="@author_handle">
<meta name="twitter:data1" content="$0">
<meta name="twitter:label1" content="Price">
<meta name="twitter:data2" content="Black">
<meta name="twitter:label2" content="Color">
<!-- Open Graph data -->
<meta property="og:title" content="E-Font Shop" />
<meta property="og:type" content="website" />
<meta property="og:url" content="" />
<meta property="og:description" content="efont, fonts, litters, web, desktop, apps, mobile" />
<meta property="og:site_name" content="E-Font Shop" />
<meta property="og:price:amount" content="0.00" />
<meta property="og:price:currency" content="USD" />
<!-- Favicon -->
<link rel="shortcut icon" href="<?php echo $this->basePath();?>/img/favicon.ico" />