		<!-- BEGIN: LAYOUT/HEADERS/HEADER-1 -->
        <!-- BEGIN: HEADER -->
        <header class="c-layout-header c-layout-header-4 c-layout-header-default-mobile" data-minimize-offset="80" ng-controller="HeaderCtrl">
            <div class="c-topbar c-topbar-light">
                <div class="container">
                    <!-- BEGIN: INLINE NAV -->
                    <nav class="c-top-menu c-pull-right">
                        <ul class="c-links c-theme-ul">
                            <li>
                                <a href="javascript:;" ng-click="notimplemented();"><?php echo $this->translate('Contact');?></a>
                            </li>
                            <li class="c-divider">|</li>
                        </ul>
                        <ul class="c-ext c-theme-ul">
                            <li class="c-lang dropdown c-last">
                            	<?php $lang = isset($_GET['language'])?strtolower($_GET['language']):'br'; ?>
                                <a href="javascript:;"><?php echo $lang;?></a>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li <?php if($lang == 'en'){?> class="active" <?php }?>><a href="<?php echo $this->url('home',array(),array('force_canonical' => true)); ?>?language=en"><?php echo $this->translate('English');?></a> </li>
                                    <li <?php if($lang == 'br'){?> class="active" <?php }?>><a href="<?php echo $this->url('home',array(),array('force_canonical' => true)); ?>?language=br"><?php echo $this->translate('Portuguese');?></a></li>
                                </ul>
                            </li>
                            <li class="c-search hide">
                                <!-- BEGIN: QUICK SEARCH -->
                                <form action="#">
                                    <input type="text" name="query" placeholder="search..." value="" class="form-control" autocomplete="off">
                                    <i class="fa fa-search"></i>
                                </form>
                                <!-- END: QUICK SEARCH -->
                            </li>
                        </ul>
                    </nav>
                    <!-- END: INLINE NAV -->
                </div>
            </div>
            <div class="c-navbar">
                <div class="container">
                    <!-- BEGIN: BRAND -->
                    <div class="c-navbar-wrapper clearfix">
                        <div class="c-brand c-pull-left">
                            <a href="javascript:;" ng-click="changeTemplateURL('/ef-welcome');" class="c-logo">
                                <img src="http://placehold.it/100x40" alt="E-Font Shop" class="c-desktop-logo">
                                <img src="http://placehold.it/100x40" alt="E-Font Shop" class="c-desktop-logo-inverse">
                                <img src="http://placehold.it/100x40" alt="E-Font Shop" class="c-mobile-logo"> </a>
                            <button class="c-hor-nav-toggler" type="button" data-target=".c-mega-menu">
                                <span class="c-line"></span>
                                <span class="c-line"></span>
                                <span class="c-line"></span>
                            </button>
                            <button class="c-topbar-toggler" type="button">
                                <i class="fa fa-ellipsis-v"></i>
                            </button>
                            <button class="c-search-toggler" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                            <button class="c-cart-toggler" type="button">
                                <i class="icon-handbag"></i>
                                <span class="c-cart-number c-theme-bg">2</span>
                            </button>
                        </div>
                        <!-- END: BRAND -->
                        <!-- BEGIN: QUICK SEARCH -->
                        <form class="c-quick-search" action="#">
                            <input type="text" name="query" placeholder="Type to search..." value="" class="form-control" autocomplete="off">
                            <span class="c-theme-link">&times;</span>
                        </form>
                        <!-- END: QUICK SEARCH -->
                        <!-- BEGIN: HOR NAV -->
                        <!-- BEGIN: LAYOUT/HEADERS/MEGA-MENU -->
                        <!-- BEGIN: MEGA MENU -->
                        <!-- Dropdown menu toggle on mobile: c-toggler class can be applied to the link arrow or link itself depending on toggle mode -->
                        <nav class="c-mega-menu c-pull-right c-mega-menu-dark c-mega-menu-dark-mobile c-fonts-uppercase c-fonts-bold">
                            <ul class="nav navbar-nav c-theme-nav">
                                <?php if(isset($this->USER_LOGGED)){?>
								<?php if($this->USER_LOGGED === true){?>
								<li class="c-active" id="nav-menu-shop-customer"><a href="javascript:;" ng-click="changeTemplateURL('/shop-customer/index', '', 'nav-menu-shop-customer');" class="c-link dropdown-toggle"><?php echo $this->translate('Dashboard');?><span class="c-arrow c-toggler"></span></a>
								<div class="dropdown-menu c-menu-type-mega c-menu-type-fullwidth" style="min-width: auto"></div></li>
								
								<?php if($this->USER_LOGGED === true && ($this->USER_PRIVILEGE_TYPE == 1)){?>
								<li id="nav-menu-shop-projects"><a href="javascript:;" ng-click="changeTemplateURL('/shop-projects/index', '', 'nav-menu-shop-projects');" class="c-link dropdown-toggle"><?php echo $this->translate('Projects');?><span class="c-arrow c-toggler"></span></a>
								<div class="dropdown-menu c-menu-type-mega c-menu-type-fullwidth" style="min-width: auto"></div></li>								
								<?php }?>
								
								<?php if($this->USER_LOGGED === true && ($this->USER_PRIVILEGE_TYPE == 2)){?>
								<li id="nav-menu-shop-admin"><a href="javascript:;" ng-click="changeTemplateURL('/shop-admin/index', '', 'nav-menu-shop-admin');" class="c-link dropdown-toggle"><?php echo $this->translate('Admin');?><span class="c-arrow c-toggler"></span></a>
								<div class="dropdown-menu c-menu-type-mega c-menu-type-fullwidth" style="min-width: auto"></div></li>									
								<?php }?>
								
								<!-- REMOVE -->
								<li id="nav-menu-shop-projects"><a href="javascript:;" ng-click="changeTemplateURL('/shop-projects/index', '', 'nav-menu-shop-projects');" class="c-link dropdown-toggle"><?php echo $this->translate('Projects');?><span class="c-arrow c-toggler"></span></a>
								<div class="dropdown-menu c-menu-type-mega c-menu-type-fullwidth" style="min-width: auto"></div></li>								
								
								<li><a href="javascript:;" class="c-link dropdown-toggle"><span class="text-muted"><?php echo $this->translate('Admin');?></span><span class="c-arrow c-toggler"></span></a>
								<div class="dropdown-menu c-menu-type-mega c-menu-type-fullwidth" style="min-width: auto"></div></li>									
								<!-- REMOVE -->
								
								<?php }?>
								<?php }?>
                                <li class="c-search-toggler-wrapper">
                                    <a href="#" class="c-btn-icon c-search-toggler">
                                        <i class="fa fa-search"></i>
                                    </a>
                                </li>
                                <li class="c-cart-toggler-wrapper">
                                    <a href="javascript:;" class="c-btn-icon c-cart-toggler">
                                        <i class="icon-handbag c-cart-icon"></i>
                                        <span id="shop-c-cart-number" class="c-cart-number c-theme-bg">0</span>
                                    </a>
                                </li>
                                <?php if(isset($this->USER_LOGGED)){?>
								<?php if($this->USER_LOGGED === true){?>
								<li><a href="<?php echo $this->url('logout',array(),array('force_canonical' => true)); ?>" class="c-btn-border-opacity-04 c-btn btn-no-focus c-btn-header btn btn-sm c-btn-border-1x c-btn-dark c-btn-circle c-btn-uppercase c-btn-sbold"><i class="icon-logout"></i> <?php echo $this->translate('Logout');?></a></li>
								<?php }?>
								<?php }else{?>
                                <li><a href="javascript:;" ng-click="changeTemplateURL('/shop-customer-account');" class="c-btn-border-opacity-04 c-btn btn-no-focus c-btn-header btn btn-sm c-btn-border-1x c-btn-dark c-btn-circle c-btn-uppercase c-btn-sbold"><i class="icon-user"></i> <?php echo $this->translate('Sign In');?></a></li>
                                <?php }?>
                            </ul>
                        </nav>
                        <!-- END: MEGA MENU -->
                        <!-- END: LAYOUT/HEADERS/MEGA-MENU -->
                        <!-- END: HOR NAV -->
                    </div>
                    <!-- BEGIN: LAYOUT/HEADERS/QUICK-CART -->
                    <!-- BEGIN: CART MENU -->
                    <div class="c-cart-menu" ng-controller="ShopCartCtrl" ng-init="viewCart();">
                        <div class="c-cart-menu-title">
                            <p class="c-cart-menu-float-l c-font-sbold">{{cart.length}} <?php echo $this->translate('item(s)');?></p>
                            <p class="c-cart-menu-float-r c-theme-font c-font-sbold">{{total | currency}}</p>
                        </div>
                        <ul class="c-cart-menu-items">
                            <li ng-repeat="(c_key, c_item) in cart">
                                <img ng-src="{{'/ef-ddig/?text=Ab&font='+c_item.form.ddig+'&size=140x140'}}" />
                                <div class="c-cart-menu-content">
                                    <p>1 x <span class="c-item-price c-theme-font">{{c_item.cart | currency}}</span></p>
                                    <a href="javascript:;" class="c-item-name c-font-sbold">{{c_item.form.name}}</a>
                                </div>
                            </li>
                            <li ng-hide="cart.length">
                                <div class="c-cart-menu-content">
                                    <span class="c-item-name c-font-sbold c-font-red">Your Shopping Cart is Empty</span>
                                </div>
                            </li>
                        </ul>
                        <div class="c-cart-menu-footer" ng-show="cart.length">
                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-md c-btn c-btn-square c-btn-grey-3 c-font-white c-font-bold c-center c-font-uppercase"><?php echo $this->translate('View Cart');?></a>
                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-checkout');" class="btn btn-md c-btn c-btn-square c-theme-btn c-font-white c-font-bold c-center c-font-uppercase"><?php echo $this->translate('Checkout');?></a>
                        </div>
                    </div>
                    <!-- END: CART MENU -->
                    <!-- END: LAYOUT/HEADERS/QUICK-CART -->
                </div>
            </div>
        </header>
        <!-- END: HEADER -->
        <!-- END: LAYOUT/HEADERS/HEADER-1 -->