			<div class="col-md-12 well text-center">
				<div class="margin-top-20">
					<i class="icon-ghost fa-5x animated rollIn" ng-class="{rollOut: hover}" ng-mouseenter="hover = true"></i>
					<h2><?php echo $this->translate('No data to display!');?></h2>
					<p> <?php echo $this->translate('Your search did not match any records.');?></p>
					
					<ul class="list-unstyled">
					<li class="bold"><?php echo $this->translate('Suggestions:');?></li>
					<li><?php echo $this->translate('Make sure that all words are spelled correctly.');?></li>
					<li><?php echo $this->translate('Try different keywords.');?></li>
					<li><?php echo $this->translate('Try more general keywords.');?></li>
					<li><?php echo $this->translate('Try fewer keywords.');?></li>
					</ul>
				</div>
			</div>