<!-- BEGIN: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
<div
	class="c-layout-breadcrumbs-1 c-subtitle c-fonts-uppercase c-fonts-bold c-bordered c-bordered-both">
	<div class="container">
		<div class="c-page-title c-pull-left">
			<h3 class="c-font-uppercase c-font-sbold"><?php echo $this->translate('Font Details');?></h3>
			<h4 class="">Page Sub Title Goes Here</h4>
		</div>
		<ul
			class="c-page-breadcrumbs c-theme-nav c-pull-right c-fonts-regular">
			<li><a href="javascript:;" ng-click="changeTemplateURL('/ef-welcome');"><?php echo $this->translate('Shop');?></a></li>
			<li>/</li>
			<li><a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');"><?php echo $this->translate('Font Grid');?></a></li>
		</ul>
	</div>
</div>
<!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->



<!-- BEGIN: PAGE CONTENT -->
<!-- BEGIN: CONTENT/SHOPS/SHOP-PRODUCT-DETAILS-4 -->
<section ng-controller="ShopProductDetailsCtrl" ng-init="getProductDetails();">
<div class="c-content-box c-size-lg c-overflow-hide c-bg-white">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="c-product-header"><div class="c-content-title-1"><h3 class="c-font-uppercase c-font-bold">{{form.name}}</h3></div></div>
				<hr />				
			</div>
			
			<div class="col-md-12">
				<!-- BEGIN LICENSE -->
				<div class="col-md-3">
					<h3 class="c-font-uppercase"><?php echo $this->translate('License Options');?></h3>
					<hr />
					
					<div class="radio" ng-repeat="(lu_key, lu_item) in licenses">
					<label><input type="radio" name="optradio" ng-value="lu_key" ng-model="license" ng-click="onChangeLicense(lu_key, lu_item.id);">{{lu_item.name}}</label>
					</div>
					<hr />
					
					<section ng-repeat="(ll_key, ll_item) in licenses" ng-show="license == ll_key">
					
					<!-- DESKTOP -->
					<div class="col-md-12" ng-show="licenses[ll_key].check_desktop">
						<small><?php echo $this->translate('DESKTOP');?>:</small>
						<select class="form-control c-square c-theme" ng-model="format[ll_key][1]" ng-change="onChangeLicenseFormats(ll_key, ll_item.id, 1);">
							<option ng-repeat="(d_key, d_item) in formats[ll_key][1]" value="{{d_key}}">  {{d_item.parameters}}</option>
						</select>						
					</div>

					<!-- WEB -->
					<div class="col-md-12" ng-show="licenses[ll_key].check_web">
						<small><?php echo $this->translate('WEB');?>:</small>
						<select class="form-control c-square c-theme" ng-model="format[ll_key][2]" ng-change="onChangeLicenseFormats(ll_key, ll_item.id, 2);">
							<option ng-repeat="(d_key, d_item) in formats[ll_key][2]" value="{{d_key}}">{{d_item.parameters}}</option>
						</select>						
					</div>

					<!-- APP -->
					<div class="col-md-12" ng-show="licenses[ll_key].check_app">
						<small><?php echo $this->translate('APP');?>:</small>
						<select class="form-control c-square c-theme" ng-model="format[ll_key][3]" ng-change="onChangeLicenseFormats(ll_key, ll_item.id, 3);">
							<option ng-repeat="(d_key, d_item) in formats[ll_key][3]" value="{{d_key}}">{{d_item.parameters}}</option>
						</select>						
					</div>
					
					<hr class="col-md-11" />
					<small><?php echo $this->translate('ONE LICENSE COVERS ALL');?>:</small><br/>
					<label class="checkbox-inline small"><i class="fa" ng-class="ll_item.check_desktop?'fa-check':'fa-close'"></i> <?php echo $this->translate('DESKTOP');?></label>
					<label class="checkbox-inline small"><i class="fa" ng-class="ll_item.check_web?'fa-check':'fa-close'"></i><?php echo $this->translate('WEB');?></label>
					<label class="checkbox-inline small"><i class="fa" ng-class="ll_item.check_app?'fa-check':'fa-close'"></i><?php echo $this->translate('APP');?></label>				
					</section>
				</div>
				<!-- END LICENSE -->
				
				<!-- BEGIN COLLECTION -->
				<div class="col-md-6">
				
					<section ng-show="licenses[license].check_desktop || licenses[license].check_web || licenses[license].check_app">
					<!-- MONEY_FAMILY -->
					<h3 class="c-font-uppercase"><?php echo $this->translate('Collection');?></h3>
					<hr />
					<table class="table table-condensed table-bordered"><tbody><tr>
						<td width="1%"><a href="javascript:;" class="btn c-btn btn-xs" ng-model="form.collapsed" ng-click="form.collapsed=!form.collapsed"><i class="fa" ng-class="form.collapsed?'fa-minus':'fa-plus'"></i></a></td>
						<td class="c-bg-dark c-bg-dark-font">&nbsp;<small>{{form.name}}&nbsp; &#8226; &nbsp; {{ form.families }} <?php echo $this->translate('Families');?> &nbsp;</small></td>
						<td class="c-bg-dark c-bg-dark-font col-md-2"><small >&nbsp;{{form.collection | currency}}</small></td></tr>
						
						<tr ng-repeat="(c_key, c_item) in families" ng-show="form.collapsed">
							<td width="1%"><button class="btn c-btn btn-xs c-btn-white"><input type="checkbox" ng-model="c_item.check_collection" ng-change="onChangeSelectedCollection(c_key, c_item.id);" /></button></td>
							<td>&nbsp;<small>{{c_item.family_name}}</small></td>
							<td class="col-md-2"><small >&nbsp;{{c_item.collection | currency}}</small></td>						
						</tr>
												
					</tbody></table>
					
					<!-- MONEY_WEIGHT -->
					<h3 class="c-font-uppercase"><?php echo $this->translate('Family');?></h3>
					<hr />
					<!-- FAMILIES -->
					<div ng-repeat="(f_key, f_item) in families">
					<table class="table table-condensed table-bordered"><tbody>
						<tr>
							<td width="1%"><a href="javascript:;" class="btn c-btn btn-xs" ng-model="f_item.collapsed" ng-click="f_item.collapsed=!f_item.collapsed"><i class="fa" ng-class="f_item.collapsed?'fa-minus':'fa-plus'"></i></a></td>
							<td class="c-bg-dark c-bg-dark-font">&nbsp;<small>{{f_item.family_name}}</small></td>
							<td class="c-bg-dark c-bg-dark-font col-md-2"><small>{{f_item.subprice | currency}}</small></td>
						</tr>
						
						<tr ng-repeat="(f_s_key, f_s_item) in styles[f_key]" ng-show="f_item.collapsed">
							<td width="1%"><button class="btn c-btn btn-xs c-btn-white"><input type="checkbox" ng-model="f_s_item.selected" ng-change="onChangeSelectedItem(f_s_key, f_key);" /></button></td>
							<td>&nbsp;<small>{{f_s_item.font_subfamily}}</small></td>
							<td class="col-md-2"><small >&nbsp;{{ f_s_item.price || 0 | currency }}</small></td>						
						</tr>
					</tbody></table>
					</div>
					</section>
				</div>
				<!-- END COLLECTION -->
				
				<!-- BEGIN PRICE -->
				<div class="col-md-3">
					<h3 class="c-font-uppercase"><?php echo $this->translate('Price');?></h3>
					<hr />
					
					<span class="c-font-30 c-font-bold">{{cart | currency}}</span>
					
					<br/><br/>
					<h3 class="c-font-uppercase"><?php echo $this->translate('SELECTED ITENS');?></h3>
					<hr />
					<section class="col-md-12" ng-repeat="(f_key, f_item) in families">
						<div class="row">
						<a href="javascript:;" class="btn c-btn btn-xs" ng-model="f_item.selected" ng-click="f_item.selected=!f_item.selected">
						<small><i class="fa" ng-class="f_item.selected?'fa-minus':'fa-plus'"></i>&nbsp;&nbsp;{{f_item.family_name}}&nbsp; &#8226; &nbsp;{{selected_numbers[f_key] || 0}} fonts</small>
						</a>
						<p ng-show="f_item.selected"><small>Styles</small></p>
						<p ng-show="f_item.selected"><small class="col-md-6" ng-repeat="(sel_key, sel_item) in styles[f_key] | selectedFilter:true" >{{sel_item.font_subfamily}}</small></p>
						</div>
						<hr class="col-md-12"/>
					</section>
					
					<div class="col-md-12">
						<div class="row"><a href="javascript:;" class="btn c-btn-dark btn-block c-btn-square" ng-disabled="cart < '1'" ng-click="AddToCart();">ADD TO CART</a></div>
					</div>
				</div>
				<!-- END PRICE -->								
			</div>
		</div>
	</div>
</div>	
<!-- END: PAGE CONTENT -->
<!-- END: CONTENT/SHOPS/SHOP-PRODUCT-DETAILS-4 -->


<!-- BEGIN: CONTENT/SHOPS/SHOP-PRODUCT-TAB-1 -->
<div class="c-content-box c-size-md c-no-padding">
	<div class="c-shop-product-tab-1" role="tabpanel">
		<div class="container">
			<ul class="nav nav-justified" role="tablist">
				<li role="presentation" class="active"><a class="c-font-uppercase c-font-bold" href="#tab-1" role="tab" data-toggle="tab"><?php echo $this->translate('Details');?></a></li>
			</ul>
		</div>
		<div class="container">
						<!-- BEGIN FONT -->
						<div>
							<div class="family-specimen" data-bind="style: { fontFamily: selectedCssFontStack, fontWeight: 'normal', fontStyle: 'normal' }">
								<table>
									<tbody>
										<tr>
											<th>36</th>
											<td><div style="font-size: 36px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=36&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>30</th>
											<td><div style="font-size: 30px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=30&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>24</th>
											<td><div style="font-size: 24px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=24&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>21</th>
											<td><div style="font-size: 21px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=21&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>18</th>
											<td><div style="font-size: 18px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=18&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>16</th>
											<td><div style="font-size: 16px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=16&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>14</th>
											<td><div style="font-size: 14px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=14&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>13</th>
											<td><div style="font-size: 13px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=13&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>12</th>
											<td><div style="font-size: 12px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=12&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>11</th>
											<td><div style="font-size: 11px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=11&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>10</th>
											<td><div style="font-size: 10px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=10&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
										<tr>
											<th>9</th>
											<td><div style="font-size: 9px"><img ng-src="{{'/ef-ddig/?ipsum=1&font='+form.ddig+'&fontsize=9&size=800x60'}}" class="img-responsive" /></div></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>

						<!-- END FONT -->
		</div>
	</div>
</div>
<!-- END: CONTENT/SHOPS/SHOP-PRODUCT-TAB-1 -->
<!-- END: PAGE CONTENT -->
</section>