            <!-- BEGIN: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <div class="c-layout-breadcrumbs-1 c-subtitle c-fonts-uppercase c-fonts-bold c-bordered c-bordered-both">
                <div class="container">
                    <div class="c-page-title c-pull-left">
                        <h3 class="c-font-uppercase c-font-sbold"><?php echo $this->translate('Cart');?></h3>
                        <h4 class="">Page Sub Title Goes Here</h4>
                    </div>
                    <ul class="c-page-breadcrumbs c-theme-nav c-pull-right c-fonts-regular">
                        <li><a href="javascript:;" ng-click="changeTemplateURL('/ef-welcome');"><?php echo $this->translate('Shop');?></a></li>
                        <li>/</li>
                        <li><a href="javascript:;"><?php echo $this->translate('Shopping Cart');?></a></li>
                    </ul>
                </div>
            </div>
            <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
            <!-- BEGIN: PAGE CONTENT -->
            <!-- BEGIN: CONTENT/SHOPS/SHOP-CART-1 -->
            <div class="c-content-box c-size-lg">
                <div class="container">
                    <div class="c-shop-cart-page-1">
                        <div class="row c-cart-table-title">
                            <div class="col-md-2 c-cart-image">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Image');?></h3>
                            </div>
                            <div class="col-md-4 c-cart-desc">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Description');?></h3>
                            </div>
                            <div class="col-md-1 c-cart-ref">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('SKU');?></h3>
                            </div>
                            <div class="col-md-2 c-cart-price">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Price');?></h3>
                            </div>
                            <div class="col-md-1 c-cart-total">
                                <h3 class="c-font-uppercase c-font-bold c-font-16 c-font-grey-2"><?php echo $this->translate('Total');?></h3>
                            </div>
                            <div class="col-md-1 c-cart-remove"></div>
                        </div>
                        <!-- BEGIN: SHOPPING CART ITEM ROW -->
                        <div class="row c-cart-table-row">
                            <h2 class="c-font-uppercase c-font-bold c-theme-bg c-font-white c-cart-item-title c-cart-item-first"><?php echo $this->translate('Item');?> 1</h2>
                            <div class="col-md-2 col-sm-3 col-xs-5 c-cart-image">
                                <img src="http://placehold.it/1200x900" /> </div>
                            <div class="col-md-4 col-sm-9 col-xs-7 c-cart-desc">
                                <h3><a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="c-font-bold c-theme-link c-font-22 c-font-dark">Font Winter J</a></h3>
                                <p><?php echo $this->translate('License Types');?>: A</p>
                            </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-ref">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold"><?php echo $this->translate('SKU');?></p>
                                <p>120715</p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-price">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold"><?php echo $this->translate('Price');?></p>
                                <p class="c-cart-price c-font-bold">$147.00</p>
                            </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-total">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold"><?php echo $this->translate('Total');?></p>
                                <p class="c-cart-price c-font-bold">$147.00</p>
                            </div>
                            <div class="col-md-1 col-sm-12 c-cart-remove">
                                <a href="#" class="c-theme-link c-cart-remove-desktop"><i class="fa fa-close"></i></a>
                                <a href="#" class="c-cart-remove-mobile btn c-btn c-btn-md c-btn-square c-btn-red c-btn-border-1x c-font-uppercase"><?php echo $this->translate('Remove item from Cart');?></a>
                            </div>
                        </div>
                        <!-- END: SHOPPING CART ITEM ROW -->
                        <!-- BEGIN: SHOPPING CART ITEM ROW -->
                        <div class="row c-cart-table-row">
                            <h2 class="c-font-uppercase c-font-bold c-theme-bg c-font-white c-cart-item-title">Item 2</h2>
                            <div class="col-md-2 col-sm-3 col-xs-5 c-cart-image">
                                <img src="http://placehold.it/1200x900" /> </div>
                            <div class="col-md-4 col-sm-9 col-xs-7 c-cart-desc">
                                <h3><a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="c-font-bold c-theme-link c-font-22 c-font-dark">Font Sports</a></h3>
                                <p>License Types: Mobile</p>
                                <p>By: User A</p>
                            </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-ref">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">SKU</p>
                                <p>160815</p>
                            </div>
                            <div class="col-md-2 col-sm-3 col-xs-6 c-cart-price">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Unit Price</p>
                                <p class="c-cart-price c-font-bold">$99.00</p>
                            </div>
                            <div class="col-md-1 col-sm-3 col-xs-6 c-cart-total">
                                <p class="c-cart-sub-title c-theme-font c-font-uppercase c-font-bold">Total</p>
                                <p class="c-cart-price c-font-bold">$99.00</p>
                            </div>
                            <div class="col-md-1 col-sm-12 c-cart-remove">
                                <a href="#" class="c-theme-link c-cart-remove-desktop"><i class="fa fa-close"></i></a>
                                <a href="#" class="c-cart-remove-mobile btn c-btn c-btn-md c-btn-square c-btn-red c-btn-border-1x c-font-uppercase">Remove item from Cart</a>
                            </div>
                        </div>
                        <!-- END: SHOPPING CART ITEM ROW -->
                        <!-- BEGIN: SUBTOTAL ITEM ROW -->
                        <div class="row">
                            <div class="c-cart-subtotal-row c-margin-t-20">
                                <div class="col-md-2 col-md-offset-9 col-sm-6 col-xs-6 c-cart-subtotal-border">
                                    <h3 class="c-font-uppercase c-font-bold c-right c-font-16 c-font-grey-2"><?php echo $this->translate('Subtotal');?></h3>
                                </div>
                                <div class="col-md-1 col-sm-6 col-xs-6 c-cart-subtotal-border">
                                    <h3 class="c-font-bold c-font-16">$246.00</h3>
                                </div>
                            </div>
                        </div>
                        <!-- END: SUBTOTAL ITEM ROW -->
                        <!-- BEGIN: SUBTOTAL ITEM ROW -->
                        <div class="row">
                            <div class="c-cart-subtotal-row">
                                <div class="col-md-2 col-md-offset-9 col-sm-6 col-xs-6 c-cart-subtotal-border">
                                    <h3 class="c-font-uppercase c-font-bold c-right c-font-16 c-font-grey-2"><?php echo $this->translate('Shipping Fee');?></h3>
                                </div>
                                <div class="col-md-1 col-sm-6 col-xs-6 c-cart-subtotal-border">
                                    <h3 class="c-font-bold c-font-16">$15.00</h3>
                                </div>
                            </div>
                        </div>
                        <!-- END: SUBTOTAL ITEM ROW -->
                        <!-- BEGIN: SUBTOTAL ITEM ROW -->
                        <div class="row">
                            <div class="c-cart-subtotal-row">
                                <div class="col-md-2 col-md-offset-9 col-sm-6 col-xs-6 c-cart-subtotal-border">
                                    <h3 class="c-font-uppercase c-font-bold c-right c-font-16 c-font-grey-2"><?php echo $this->translate('Grand Total');?></h3>
                                </div>
                                <div class="col-md-1 col-sm-6 col-xs-6 c-cart-subtotal-border">
                                    <h3 class="c-font-bold c-font-16">$261.00</h3>
                                </div>
                            </div>
                        </div>
                        <!-- END: SUBTOTAL ITEM ROW -->
                        <div class="c-cart-buttons">
                            <a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn c-btn btn-lg c-btn-red c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-l"><?php echo $this->translate('Continue Shopping');?></a>
                            <a href="javascript:;"  ng-click="changeTemplateURL('/shop-checkout');" class="btn c-btn btn-lg c-theme-btn c-btn-square c-font-white c-font-bold c-font-uppercase c-cart-float-r"><?php echo $this->translate('Checkout');?></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END: CONTENT/SHOPS/SHOP-CART-1 -->

            <!-- BEGIN: CONTENT/STEPS/STEPS-3 -->
            <div class="c-content-box c-size-md c-theme-bg">
                <div class="container">
                    <div class="c-content-step-3 c-font-white">
                        <div class="row">
                            <div class="col-md-4 c-steps-3-block">
                                <i class="fa fa-truck"></i>
                                <div class="c-steps-3-title">
                                    <h2 class="c-font-white c-font-uppercase c-font-30 c-font-thin"><?php echo $this->translate('Email shipping');?></h2>
                                    <em><?php echo $this->translate('Express delivery after payment');?></em>
                                </div>
                                <span>&nbsp;</span>
                            </div>
                            <div class="col-md-4 c-steps-3-block">
                                <i class="fa fa-gift"></i>
                                <div class="c-steps-3-title">
                                    <h2 class="c-font-white c-font-uppercase c-font-30 c-font-thin"><?php echo $this->translate('Download');?></h2>
                                    <em><?php echo $this->translate('Download by link email');?></em>
                                </div>
                                <span>&nbsp;</span>
                            </div>
                            <div class="col-md-4 c-steps-3-block">
                                <i class="fa fa-envelope"></i>
                                <div class="c-steps-3-title">
                                    <h2 class="c-font-white c-font-uppercase c-font-30 c-font-thin">support@example.com</h2>
                                    <em><?php echo $this->translate('24/7 customer care available');?></em>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END: CONTENT/STEPS/STEPS-3 -->
            <!-- END: PAGE CONTENT -->
