<section ng-controller="ShopProductListCtrl" ng-init="initProductList();">
<div class="row">
	<div class="col-md-12 col-sm-12 c-margin-b-20" ng-repeat="(p_key, p_item) in products">
			<div class="c-content-product-2 c-bg-white">
				<div class="c-content-overlay">
					<div class="c-overlay-wrapper">
						<div class="c-overlay-content">
							<a href="javascript:;" ng-click="goDetails(p_item.id);" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
						</div>
					</div>
					<div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 200px;"><img ng-src="{{'/ef-ddig/?text='+(p_item.name | escape)+'&font='+p_item.ddig}}" class="img-responsive" /></div>
				</div>
				<div class="c-info">
					<p class="c-title c-font-18 c-font-slim ">{{p_item.name}}</p>
					<!-- <p class="c-title c-font-18 c-font-slim ">{{p_item.number_families || 0}} <?php //echo $this->translate('Family');?> | </p> -->
				</div>
			</div>
		</div>
</div>	
</section>