<section ng-controller="ShopProductListCtrl" ng-init="initProductList();">
<div class="row">
	<div class="col-md-12 col-sm-12 c-margin-b-20" ng-repeat="(p_key, p_item) in products">
			<div class="c-content-product-2 c-bg-white">
				<div class="c-content-overlay">
					<div class="c-overlay-wrapper">
						<div class="c-overlay-content">
							<a href="javascript:;" ng-click="changeTemplateURL('/shop-product-details');" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
						</div>
					</div>
					<div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 270px;"  background-image-directive="{{p_item.banner}}"></div>
				</div>
				<div class="c-info">
					<p class="c-title c-font-18 c-font-slim">Acumin</p>
				</div>
				<div class="btn-group btn-group-justified" role="group">
					<div class="btn-group c-border-top" role="group">
						<a href="javascript:;" ng-click="changeTemplateURL('/shop-product-list');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Qana</a>
					</div>
					<div class="btn-group c-border-left c-border-top" role="group">
						<a href="javascript:;" ng-click="changeTemplateURL('/shop-cart');" class="btn btn-lg c-btn-white c-btn-uppercase c-btn-square c-font-grey-3 c-font-white-hover c-bg-red-2-hover c-btn-product">Cart</a>
					</div>
				</div>
			</div>
		</div>
</div>	
</section>